@startuml
class SolverTests {
    + Setup() : void
    + Solver_GeneratesOptimalSolution() : void
    + Solver_SettingsChange() : void
    + Solver_CallsProgressCallback() : void
    + GeneratedRoute_VisitsAll() : void
}
SolverTests --> "_net" Network
SolverTests --> "_solver" AnnealingSolver
@enduml
