/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TflApiPresentationEntitiesCarParkOccupancy
    /// </summary>
    [DataContract]
    public partial class TflApiPresentationEntitiesCarParkOccupancy :  IEquatable<TflApiPresentationEntitiesCarParkOccupancy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TflApiPresentationEntitiesCarParkOccupancy" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="bays">bays.</param>
        /// <param name="name">name.</param>
        /// <param name="carParkDetailsUrl">carParkDetailsUrl.</param>
        public TflApiPresentationEntitiesCarParkOccupancy(string id = default(string), List<TflApiPresentationEntitiesBay> bays = default(List<TflApiPresentationEntitiesBay>), string name = default(string), string carParkDetailsUrl = default(string))
        {
            this.Id = id;
            this.Bays = bays;
            this.Name = name;
            this.CarParkDetailsUrl = carParkDetailsUrl;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Bays
        /// </summary>
        [DataMember(Name="bays", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesBay> Bays { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CarParkDetailsUrl
        /// </summary>
        [DataMember(Name="carParkDetailsUrl", EmitDefaultValue=false)]
        public string CarParkDetailsUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TflApiPresentationEntitiesCarParkOccupancy {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Bays: ").Append(Bays).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CarParkDetailsUrl: ").Append(CarParkDetailsUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TflApiPresentationEntitiesCarParkOccupancy);
        }

        /// <summary>
        /// Returns true if TflApiPresentationEntitiesCarParkOccupancy instances are equal
        /// </summary>
        /// <param name="input">Instance of TflApiPresentationEntitiesCarParkOccupancy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TflApiPresentationEntitiesCarParkOccupancy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Bays == input.Bays ||
                    this.Bays != null &&
                    this.Bays.SequenceEqual(input.Bays)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CarParkDetailsUrl == input.CarParkDetailsUrl ||
                    (this.CarParkDetailsUrl != null &&
                    this.CarParkDetailsUrl.Equals(input.CarParkDetailsUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Bays != null)
                    hashCode = hashCode * 59 + this.Bays.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.CarParkDetailsUrl != null)
                    hashCode = hashCode * 59 + this.CarParkDetailsUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
