/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TflApiPresentationEntitiesRoadDisruption
    /// </summary>
    [DataContract]
    public partial class TflApiPresentationEntitiesRoadDisruption :  IEquatable<TflApiPresentationEntitiesRoadDisruption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TflApiPresentationEntitiesRoadDisruption" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the road disruption.</param>
        /// <param name="url">URL to retrieve this road disruption.</param>
        /// <param name="point">Latitude and longitude (WGS84) of the centroid of the disruption, stored in a geoJSON-formatted string..</param>
        /// <param name="severity">A description of the severity of the disruption..</param>
        /// <param name="ordinal">An ordinal of the disruption based on severity, level of interest and corridor..</param>
        /// <param name="category">Describes the nature of disruption e.g. Traffic Incidents, Works.</param>
        /// <param name="subCategory">Describes the sub-category of disruption e.g. Collapsed Manhole, Abnormal Load.</param>
        /// <param name="comments">Full text of comments describing the disruption, including details of any road closures and diversions, where appropriate..</param>
        /// <param name="currentUpdate">Text of the most recent update from the LSTCC on the state of the               disruption, including the current traffic impact and any advice to               road users..</param>
        /// <param name="currentUpdateDateTime">The time when the last CurrentUpdate description was recorded,               or null if no CurrentUpdate has been applied..</param>
        /// <param name="corridorIds">The Ids of affected corridors, if any..</param>
        /// <param name="startDateTime">The date and time which the disruption started. For a planned disruption (i.e. planned road works) this date will be in the future.              For unplanned disruptions, this will default to the date on which the disruption was first recorded, but may be adjusted by the operator..</param>
        /// <param name="endDateTime">The date and time on which the disruption ended. For planned disruptions, this date will have a valid value. For unplanned               disruptions in progress, this field will be omitted..</param>
        /// <param name="lastModifiedTime">The date and time on which the disruption was last modified in the system. This information can reliably be used by a developer to quickly              compare two instances of the same disruption to determine if it has been changed..</param>
        /// <param name="levelOfInterest">This describes the level of potential impact on traffic operations of the disruption.               High &#x3D; e.g. a one-off disruption on a major or high profile route which will require a high level of operational attention               Medium &#x3D; This is the default value               Low &#x3D; e.g. a frequently occurring disruption which is well known.</param>
        /// <param name="location">Main road name / number (borough) or preset area name where the disruption is located. This might be useful for a map popup where space is limited..</param>
        /// <param name="status">This describes the status of the disruption.                Active &#x3D; currently in progress               Active Long Term &#x3D; currently in progress and long term              Scheduled &#x3D; scheduled to start within the next 180 days              Recurring Works &#x3D; planned maintenance works that follow a regular routine or pattern and whose next occurrence is to start within the next 180 days.              Recently Cleared &#x3D; recently cleared in the last 24 hours              Note that the status of Scheduled or Recurring Works disruptions will change to Active when they start, and will change status again when they end..</param>
        /// <param name="geography">Geography version of Point for output as GeoJSON.              Can not use Geometry in a consistent way as non-TIMS disruptions do not have a polygon.</param>
        /// <param name="geometry">GeoJSON formatted latitude/longitude (WGS84) pairs forming an enclosed polyline or polygon. The polygon will only be included where affected streets information              is not available for the disruption, would be inappropriate (e.g. a very large number of streets), or is centred on an area without streets (e.g. a football stadium)..</param>
        /// <param name="streets">A collection of zero or more streets affected by the disruption..</param>
        /// <param name="isProvisional">True if the disruption is planned on a future date that is open to change.</param>
        /// <param name="hasClosures">True if any of the affected Streets have a \&quot;Full Closure\&quot; status, false otherwise. A RoadDisruption that has HasClosures is considered a               Severe or Serious disruption for severity filtering purposes..</param>
        /// <param name="linkText">The text of any associated link.</param>
        /// <param name="linkUrl">The url of any associated link.</param>
        /// <param name="roadProject">Any associated road project.</param>
        /// <param name="publishStartDate">TDM Additional properties.</param>
        /// <param name="publishEndDate">publishEndDate.</param>
        /// <param name="timeFrame">timeFrame.</param>
        /// <param name="roadDisruptionLines">roadDisruptionLines.</param>
        /// <param name="roadDisruptionImpactAreas">roadDisruptionImpactAreas.</param>
        /// <param name="recurringSchedules">recurringSchedules.</param>
        public TflApiPresentationEntitiesRoadDisruption(string id = default(string), string url = default(string), string point = default(string), string severity = default(string), int? ordinal = default(int?), string category = default(string), string subCategory = default(string), string comments = default(string), string currentUpdate = default(string), DateTime? currentUpdateDateTime = default(DateTime?), List<string> corridorIds = default(List<string>), DateTime? startDateTime = default(DateTime?), DateTime? endDateTime = default(DateTime?), DateTime? lastModifiedTime = default(DateTime?), string levelOfInterest = default(string), string location = default(string), string status = default(string), SystemDataSpatialDbGeography geography = default(SystemDataSpatialDbGeography), SystemDataSpatialDbGeography geometry = default(SystemDataSpatialDbGeography), List<TflApiPresentationEntitiesStreet> streets = default(List<TflApiPresentationEntitiesStreet>), bool? isProvisional = default(bool?), bool? hasClosures = default(bool?), string linkText = default(string), string linkUrl = default(string), TflApiPresentationEntitiesRoadProject roadProject = default(TflApiPresentationEntitiesRoadProject), DateTime? publishStartDate = default(DateTime?), DateTime? publishEndDate = default(DateTime?), string timeFrame = default(string), List<TflApiPresentationEntitiesRoadDisruptionLine> roadDisruptionLines = default(List<TflApiPresentationEntitiesRoadDisruptionLine>), List<TflApiPresentationEntitiesRoadDisruptionImpactArea> roadDisruptionImpactAreas = default(List<TflApiPresentationEntitiesRoadDisruptionImpactArea>), List<TflApiPresentationEntitiesRoadDisruptionSchedule> recurringSchedules = default(List<TflApiPresentationEntitiesRoadDisruptionSchedule>))
        {
            this.Id = id;
            this.Url = url;
            this.Point = point;
            this.Severity = severity;
            this.Ordinal = ordinal;
            this.Category = category;
            this.SubCategory = subCategory;
            this.Comments = comments;
            this.CurrentUpdate = currentUpdate;
            this.CurrentUpdateDateTime = currentUpdateDateTime;
            this.CorridorIds = corridorIds;
            this.StartDateTime = startDateTime;
            this.EndDateTime = endDateTime;
            this.LastModifiedTime = lastModifiedTime;
            this.LevelOfInterest = levelOfInterest;
            this.Location = location;
            this.Status = status;
            this.Geography = geography;
            this.Geometry = geometry;
            this.Streets = streets;
            this.IsProvisional = isProvisional;
            this.HasClosures = hasClosures;
            this.LinkText = linkText;
            this.LinkUrl = linkUrl;
            this.RoadProject = roadProject;
            this.PublishStartDate = publishStartDate;
            this.PublishEndDate = publishEndDate;
            this.TimeFrame = timeFrame;
            this.RoadDisruptionLines = roadDisruptionLines;
            this.RoadDisruptionImpactAreas = roadDisruptionImpactAreas;
            this.RecurringSchedules = recurringSchedules;
        }
        
        /// <summary>
        /// Unique identifier for the road disruption
        /// </summary>
        /// <value>Unique identifier for the road disruption</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// URL to retrieve this road disruption
        /// </summary>
        /// <value>URL to retrieve this road disruption</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Latitude and longitude (WGS84) of the centroid of the disruption, stored in a geoJSON-formatted string.
        /// </summary>
        /// <value>Latitude and longitude (WGS84) of the centroid of the disruption, stored in a geoJSON-formatted string.</value>
        [DataMember(Name="point", EmitDefaultValue=false)]
        public string Point { get; set; }

        /// <summary>
        /// A description of the severity of the disruption.
        /// </summary>
        /// <value>A description of the severity of the disruption.</value>
        [DataMember(Name="severity", EmitDefaultValue=false)]
        public string Severity { get; set; }

        /// <summary>
        /// An ordinal of the disruption based on severity, level of interest and corridor.
        /// </summary>
        /// <value>An ordinal of the disruption based on severity, level of interest and corridor.</value>
        [DataMember(Name="ordinal", EmitDefaultValue=false)]
        public int? Ordinal { get; set; }

        /// <summary>
        /// Describes the nature of disruption e.g. Traffic Incidents, Works
        /// </summary>
        /// <value>Describes the nature of disruption e.g. Traffic Incidents, Works</value>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public string Category { get; set; }

        /// <summary>
        /// Describes the sub-category of disruption e.g. Collapsed Manhole, Abnormal Load
        /// </summary>
        /// <value>Describes the sub-category of disruption e.g. Collapsed Manhole, Abnormal Load</value>
        [DataMember(Name="subCategory", EmitDefaultValue=false)]
        public string SubCategory { get; set; }

        /// <summary>
        /// Full text of comments describing the disruption, including details of any road closures and diversions, where appropriate.
        /// </summary>
        /// <value>Full text of comments describing the disruption, including details of any road closures and diversions, where appropriate.</value>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public string Comments { get; set; }

        /// <summary>
        /// Text of the most recent update from the LSTCC on the state of the               disruption, including the current traffic impact and any advice to               road users.
        /// </summary>
        /// <value>Text of the most recent update from the LSTCC on the state of the               disruption, including the current traffic impact and any advice to               road users.</value>
        [DataMember(Name="currentUpdate", EmitDefaultValue=false)]
        public string CurrentUpdate { get; set; }

        /// <summary>
        /// The time when the last CurrentUpdate description was recorded,               or null if no CurrentUpdate has been applied.
        /// </summary>
        /// <value>The time when the last CurrentUpdate description was recorded,               or null if no CurrentUpdate has been applied.</value>
        [DataMember(Name="currentUpdateDateTime", EmitDefaultValue=false)]
        public DateTime? CurrentUpdateDateTime { get; set; }

        /// <summary>
        /// The Ids of affected corridors, if any.
        /// </summary>
        /// <value>The Ids of affected corridors, if any.</value>
        [DataMember(Name="corridorIds", EmitDefaultValue=false)]
        public List<string> CorridorIds { get; set; }

        /// <summary>
        /// The date and time which the disruption started. For a planned disruption (i.e. planned road works) this date will be in the future.              For unplanned disruptions, this will default to the date on which the disruption was first recorded, but may be adjusted by the operator.
        /// </summary>
        /// <value>The date and time which the disruption started. For a planned disruption (i.e. planned road works) this date will be in the future.              For unplanned disruptions, this will default to the date on which the disruption was first recorded, but may be adjusted by the operator.</value>
        [DataMember(Name="startDateTime", EmitDefaultValue=false)]
        public DateTime? StartDateTime { get; set; }

        /// <summary>
        /// The date and time on which the disruption ended. For planned disruptions, this date will have a valid value. For unplanned               disruptions in progress, this field will be omitted.
        /// </summary>
        /// <value>The date and time on which the disruption ended. For planned disruptions, this date will have a valid value. For unplanned               disruptions in progress, this field will be omitted.</value>
        [DataMember(Name="endDateTime", EmitDefaultValue=false)]
        public DateTime? EndDateTime { get; set; }

        /// <summary>
        /// The date and time on which the disruption was last modified in the system. This information can reliably be used by a developer to quickly              compare two instances of the same disruption to determine if it has been changed.
        /// </summary>
        /// <value>The date and time on which the disruption was last modified in the system. This information can reliably be used by a developer to quickly              compare two instances of the same disruption to determine if it has been changed.</value>
        [DataMember(Name="lastModifiedTime", EmitDefaultValue=false)]
        public DateTime? LastModifiedTime { get; set; }

        /// <summary>
        /// This describes the level of potential impact on traffic operations of the disruption.               High &#x3D; e.g. a one-off disruption on a major or high profile route which will require a high level of operational attention               Medium &#x3D; This is the default value               Low &#x3D; e.g. a frequently occurring disruption which is well known
        /// </summary>
        /// <value>This describes the level of potential impact on traffic operations of the disruption.               High &#x3D; e.g. a one-off disruption on a major or high profile route which will require a high level of operational attention               Medium &#x3D; This is the default value               Low &#x3D; e.g. a frequently occurring disruption which is well known</value>
        [DataMember(Name="levelOfInterest", EmitDefaultValue=false)]
        public string LevelOfInterest { get; set; }

        /// <summary>
        /// Main road name / number (borough) or preset area name where the disruption is located. This might be useful for a map popup where space is limited.
        /// </summary>
        /// <value>Main road name / number (borough) or preset area name where the disruption is located. This might be useful for a map popup where space is limited.</value>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public string Location { get; set; }

        /// <summary>
        /// This describes the status of the disruption.                Active &#x3D; currently in progress               Active Long Term &#x3D; currently in progress and long term              Scheduled &#x3D; scheduled to start within the next 180 days              Recurring Works &#x3D; planned maintenance works that follow a regular routine or pattern and whose next occurrence is to start within the next 180 days.              Recently Cleared &#x3D; recently cleared in the last 24 hours              Note that the status of Scheduled or Recurring Works disruptions will change to Active when they start, and will change status again when they end.
        /// </summary>
        /// <value>This describes the status of the disruption.                Active &#x3D; currently in progress               Active Long Term &#x3D; currently in progress and long term              Scheduled &#x3D; scheduled to start within the next 180 days              Recurring Works &#x3D; planned maintenance works that follow a regular routine or pattern and whose next occurrence is to start within the next 180 days.              Recently Cleared &#x3D; recently cleared in the last 24 hours              Note that the status of Scheduled or Recurring Works disruptions will change to Active when they start, and will change status again when they end.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Geography version of Point for output as GeoJSON.              Can not use Geometry in a consistent way as non-TIMS disruptions do not have a polygon
        /// </summary>
        /// <value>Geography version of Point for output as GeoJSON.              Can not use Geometry in a consistent way as non-TIMS disruptions do not have a polygon</value>
        [DataMember(Name="geography", EmitDefaultValue=false)]
        public SystemDataSpatialDbGeography Geography { get; set; }

        /// <summary>
        /// GeoJSON formatted latitude/longitude (WGS84) pairs forming an enclosed polyline or polygon. The polygon will only be included where affected streets information              is not available for the disruption, would be inappropriate (e.g. a very large number of streets), or is centred on an area without streets (e.g. a football stadium).
        /// </summary>
        /// <value>GeoJSON formatted latitude/longitude (WGS84) pairs forming an enclosed polyline or polygon. The polygon will only be included where affected streets information              is not available for the disruption, would be inappropriate (e.g. a very large number of streets), or is centred on an area without streets (e.g. a football stadium).</value>
        [DataMember(Name="geometry", EmitDefaultValue=false)]
        public SystemDataSpatialDbGeography Geometry { get; set; }

        /// <summary>
        /// A collection of zero or more streets affected by the disruption.
        /// </summary>
        /// <value>A collection of zero or more streets affected by the disruption.</value>
        [DataMember(Name="streets", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesStreet> Streets { get; set; }

        /// <summary>
        /// True if the disruption is planned on a future date that is open to change
        /// </summary>
        /// <value>True if the disruption is planned on a future date that is open to change</value>
        [DataMember(Name="isProvisional", EmitDefaultValue=false)]
        public bool? IsProvisional { get; set; }

        /// <summary>
        /// True if any of the affected Streets have a \&quot;Full Closure\&quot; status, false otherwise. A RoadDisruption that has HasClosures is considered a               Severe or Serious disruption for severity filtering purposes.
        /// </summary>
        /// <value>True if any of the affected Streets have a \&quot;Full Closure\&quot; status, false otherwise. A RoadDisruption that has HasClosures is considered a               Severe or Serious disruption for severity filtering purposes.</value>
        [DataMember(Name="hasClosures", EmitDefaultValue=false)]
        public bool? HasClosures { get; set; }

        /// <summary>
        /// The text of any associated link
        /// </summary>
        /// <value>The text of any associated link</value>
        [DataMember(Name="linkText", EmitDefaultValue=false)]
        public string LinkText { get; set; }

        /// <summary>
        /// The url of any associated link
        /// </summary>
        /// <value>The url of any associated link</value>
        [DataMember(Name="linkUrl", EmitDefaultValue=false)]
        public string LinkUrl { get; set; }

        /// <summary>
        /// Any associated road project
        /// </summary>
        /// <value>Any associated road project</value>
        [DataMember(Name="roadProject", EmitDefaultValue=false)]
        public TflApiPresentationEntitiesRoadProject RoadProject { get; set; }

        /// <summary>
        /// TDM Additional properties
        /// </summary>
        /// <value>TDM Additional properties</value>
        [DataMember(Name="publishStartDate", EmitDefaultValue=false)]
        public DateTime? PublishStartDate { get; set; }

        /// <summary>
        /// Gets or Sets PublishEndDate
        /// </summary>
        [DataMember(Name="publishEndDate", EmitDefaultValue=false)]
        public DateTime? PublishEndDate { get; set; }

        /// <summary>
        /// Gets or Sets TimeFrame
        /// </summary>
        [DataMember(Name="timeFrame", EmitDefaultValue=false)]
        public string TimeFrame { get; set; }

        /// <summary>
        /// Gets or Sets RoadDisruptionLines
        /// </summary>
        [DataMember(Name="roadDisruptionLines", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesRoadDisruptionLine> RoadDisruptionLines { get; set; }

        /// <summary>
        /// Gets or Sets RoadDisruptionImpactAreas
        /// </summary>
        [DataMember(Name="roadDisruptionImpactAreas", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesRoadDisruptionImpactArea> RoadDisruptionImpactAreas { get; set; }

        /// <summary>
        /// Gets or Sets RecurringSchedules
        /// </summary>
        [DataMember(Name="recurringSchedules", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesRoadDisruptionSchedule> RecurringSchedules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TflApiPresentationEntitiesRoadDisruption {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Point: ").Append(Point).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Ordinal: ").Append(Ordinal).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  SubCategory: ").Append(SubCategory).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  CurrentUpdate: ").Append(CurrentUpdate).Append("\n");
            sb.Append("  CurrentUpdateDateTime: ").Append(CurrentUpdateDateTime).Append("\n");
            sb.Append("  CorridorIds: ").Append(CorridorIds).Append("\n");
            sb.Append("  StartDateTime: ").Append(StartDateTime).Append("\n");
            sb.Append("  EndDateTime: ").Append(EndDateTime).Append("\n");
            sb.Append("  LastModifiedTime: ").Append(LastModifiedTime).Append("\n");
            sb.Append("  LevelOfInterest: ").Append(LevelOfInterest).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Geography: ").Append(Geography).Append("\n");
            sb.Append("  Geometry: ").Append(Geometry).Append("\n");
            sb.Append("  Streets: ").Append(Streets).Append("\n");
            sb.Append("  IsProvisional: ").Append(IsProvisional).Append("\n");
            sb.Append("  HasClosures: ").Append(HasClosures).Append("\n");
            sb.Append("  LinkText: ").Append(LinkText).Append("\n");
            sb.Append("  LinkUrl: ").Append(LinkUrl).Append("\n");
            sb.Append("  RoadProject: ").Append(RoadProject).Append("\n");
            sb.Append("  PublishStartDate: ").Append(PublishStartDate).Append("\n");
            sb.Append("  PublishEndDate: ").Append(PublishEndDate).Append("\n");
            sb.Append("  TimeFrame: ").Append(TimeFrame).Append("\n");
            sb.Append("  RoadDisruptionLines: ").Append(RoadDisruptionLines).Append("\n");
            sb.Append("  RoadDisruptionImpactAreas: ").Append(RoadDisruptionImpactAreas).Append("\n");
            sb.Append("  RecurringSchedules: ").Append(RecurringSchedules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TflApiPresentationEntitiesRoadDisruption);
        }

        /// <summary>
        /// Returns true if TflApiPresentationEntitiesRoadDisruption instances are equal
        /// </summary>
        /// <param name="input">Instance of TflApiPresentationEntitiesRoadDisruption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TflApiPresentationEntitiesRoadDisruption input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.Point == input.Point ||
                    (this.Point != null &&
                    this.Point.Equals(input.Point))
                ) && 
                (
                    this.Severity == input.Severity ||
                    (this.Severity != null &&
                    this.Severity.Equals(input.Severity))
                ) && 
                (
                    this.Ordinal == input.Ordinal ||
                    (this.Ordinal != null &&
                    this.Ordinal.Equals(input.Ordinal))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.SubCategory == input.SubCategory ||
                    (this.SubCategory != null &&
                    this.SubCategory.Equals(input.SubCategory))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.CurrentUpdate == input.CurrentUpdate ||
                    (this.CurrentUpdate != null &&
                    this.CurrentUpdate.Equals(input.CurrentUpdate))
                ) && 
                (
                    this.CurrentUpdateDateTime == input.CurrentUpdateDateTime ||
                    (this.CurrentUpdateDateTime != null &&
                    this.CurrentUpdateDateTime.Equals(input.CurrentUpdateDateTime))
                ) && 
                (
                    this.CorridorIds == input.CorridorIds ||
                    this.CorridorIds != null &&
                    this.CorridorIds.SequenceEqual(input.CorridorIds)
                ) && 
                (
                    this.StartDateTime == input.StartDateTime ||
                    (this.StartDateTime != null &&
                    this.StartDateTime.Equals(input.StartDateTime))
                ) && 
                (
                    this.EndDateTime == input.EndDateTime ||
                    (this.EndDateTime != null &&
                    this.EndDateTime.Equals(input.EndDateTime))
                ) && 
                (
                    this.LastModifiedTime == input.LastModifiedTime ||
                    (this.LastModifiedTime != null &&
                    this.LastModifiedTime.Equals(input.LastModifiedTime))
                ) && 
                (
                    this.LevelOfInterest == input.LevelOfInterest ||
                    (this.LevelOfInterest != null &&
                    this.LevelOfInterest.Equals(input.LevelOfInterest))
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Geography == input.Geography ||
                    (this.Geography != null &&
                    this.Geography.Equals(input.Geography))
                ) && 
                (
                    this.Geometry == input.Geometry ||
                    (this.Geometry != null &&
                    this.Geometry.Equals(input.Geometry))
                ) && 
                (
                    this.Streets == input.Streets ||
                    this.Streets != null &&
                    this.Streets.SequenceEqual(input.Streets)
                ) && 
                (
                    this.IsProvisional == input.IsProvisional ||
                    (this.IsProvisional != null &&
                    this.IsProvisional.Equals(input.IsProvisional))
                ) && 
                (
                    this.HasClosures == input.HasClosures ||
                    (this.HasClosures != null &&
                    this.HasClosures.Equals(input.HasClosures))
                ) && 
                (
                    this.LinkText == input.LinkText ||
                    (this.LinkText != null &&
                    this.LinkText.Equals(input.LinkText))
                ) && 
                (
                    this.LinkUrl == input.LinkUrl ||
                    (this.LinkUrl != null &&
                    this.LinkUrl.Equals(input.LinkUrl))
                ) && 
                (
                    this.RoadProject == input.RoadProject ||
                    (this.RoadProject != null &&
                    this.RoadProject.Equals(input.RoadProject))
                ) && 
                (
                    this.PublishStartDate == input.PublishStartDate ||
                    (this.PublishStartDate != null &&
                    this.PublishStartDate.Equals(input.PublishStartDate))
                ) && 
                (
                    this.PublishEndDate == input.PublishEndDate ||
                    (this.PublishEndDate != null &&
                    this.PublishEndDate.Equals(input.PublishEndDate))
                ) && 
                (
                    this.TimeFrame == input.TimeFrame ||
                    (this.TimeFrame != null &&
                    this.TimeFrame.Equals(input.TimeFrame))
                ) && 
                (
                    this.RoadDisruptionLines == input.RoadDisruptionLines ||
                    this.RoadDisruptionLines != null &&
                    this.RoadDisruptionLines.SequenceEqual(input.RoadDisruptionLines)
                ) && 
                (
                    this.RoadDisruptionImpactAreas == input.RoadDisruptionImpactAreas ||
                    this.RoadDisruptionImpactAreas != null &&
                    this.RoadDisruptionImpactAreas.SequenceEqual(input.RoadDisruptionImpactAreas)
                ) && 
                (
                    this.RecurringSchedules == input.RecurringSchedules ||
                    this.RecurringSchedules != null &&
                    this.RecurringSchedules.SequenceEqual(input.RecurringSchedules)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.Point != null)
                    hashCode = hashCode * 59 + this.Point.GetHashCode();
                if (this.Severity != null)
                    hashCode = hashCode * 59 + this.Severity.GetHashCode();
                if (this.Ordinal != null)
                    hashCode = hashCode * 59 + this.Ordinal.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.SubCategory != null)
                    hashCode = hashCode * 59 + this.SubCategory.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.CurrentUpdate != null)
                    hashCode = hashCode * 59 + this.CurrentUpdate.GetHashCode();
                if (this.CurrentUpdateDateTime != null)
                    hashCode = hashCode * 59 + this.CurrentUpdateDateTime.GetHashCode();
                if (this.CorridorIds != null)
                    hashCode = hashCode * 59 + this.CorridorIds.GetHashCode();
                if (this.StartDateTime != null)
                    hashCode = hashCode * 59 + this.StartDateTime.GetHashCode();
                if (this.EndDateTime != null)
                    hashCode = hashCode * 59 + this.EndDateTime.GetHashCode();
                if (this.LastModifiedTime != null)
                    hashCode = hashCode * 59 + this.LastModifiedTime.GetHashCode();
                if (this.LevelOfInterest != null)
                    hashCode = hashCode * 59 + this.LevelOfInterest.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Geography != null)
                    hashCode = hashCode * 59 + this.Geography.GetHashCode();
                if (this.Geometry != null)
                    hashCode = hashCode * 59 + this.Geometry.GetHashCode();
                if (this.Streets != null)
                    hashCode = hashCode * 59 + this.Streets.GetHashCode();
                if (this.IsProvisional != null)
                    hashCode = hashCode * 59 + this.IsProvisional.GetHashCode();
                if (this.HasClosures != null)
                    hashCode = hashCode * 59 + this.HasClosures.GetHashCode();
                if (this.LinkText != null)
                    hashCode = hashCode * 59 + this.LinkText.GetHashCode();
                if (this.LinkUrl != null)
                    hashCode = hashCode * 59 + this.LinkUrl.GetHashCode();
                if (this.RoadProject != null)
                    hashCode = hashCode * 59 + this.RoadProject.GetHashCode();
                if (this.PublishStartDate != null)
                    hashCode = hashCode * 59 + this.PublishStartDate.GetHashCode();
                if (this.PublishEndDate != null)
                    hashCode = hashCode * 59 + this.PublishEndDate.GetHashCode();
                if (this.TimeFrame != null)
                    hashCode = hashCode * 59 + this.TimeFrame.GetHashCode();
                if (this.RoadDisruptionLines != null)
                    hashCode = hashCode * 59 + this.RoadDisruptionLines.GetHashCode();
                if (this.RoadDisruptionImpactAreas != null)
                    hashCode = hashCode * 59 + this.RoadDisruptionImpactAreas.GetHashCode();
                if (this.RecurringSchedules != null)
                    hashCode = hashCode * 59 + this.RecurringSchedules.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
