/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TflApiPresentationEntitiesFaresJourney
    /// </summary>
    [DataContract]
    public partial class TflApiPresentationEntitiesFaresJourney :  IEquatable<TflApiPresentationEntitiesFaresJourney>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TflApiPresentationEntitiesFaresJourney" /> class.
        /// </summary>
        /// <param name="fromStation">fromStation.</param>
        /// <param name="toStation">toStation.</param>
        public TflApiPresentationEntitiesFaresJourney(TflApiPresentationEntitiesFaresFareStation fromStation = default(TflApiPresentationEntitiesFaresFareStation), TflApiPresentationEntitiesFaresFareStation toStation = default(TflApiPresentationEntitiesFaresFareStation))
        {
            this.FromStation = fromStation;
            this.ToStation = toStation;
        }
        
        /// <summary>
        /// Gets or Sets FromStation
        /// </summary>
        [DataMember(Name="fromStation", EmitDefaultValue=false)]
        public TflApiPresentationEntitiesFaresFareStation FromStation { get; set; }

        /// <summary>
        /// Gets or Sets ToStation
        /// </summary>
        [DataMember(Name="toStation", EmitDefaultValue=false)]
        public TflApiPresentationEntitiesFaresFareStation ToStation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TflApiPresentationEntitiesFaresJourney {\n");
            sb.Append("  FromStation: ").Append(FromStation).Append("\n");
            sb.Append("  ToStation: ").Append(ToStation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TflApiPresentationEntitiesFaresJourney);
        }

        /// <summary>
        /// Returns true if TflApiPresentationEntitiesFaresJourney instances are equal
        /// </summary>
        /// <param name="input">Instance of TflApiPresentationEntitiesFaresJourney to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TflApiPresentationEntitiesFaresJourney input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FromStation == input.FromStation ||
                    (this.FromStation != null &&
                    this.FromStation.Equals(input.FromStation))
                ) && 
                (
                    this.ToStation == input.ToStation ||
                    (this.ToStation != null &&
                    this.ToStation.Equals(input.ToStation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FromStation != null)
                    hashCode = hashCode * 59 + this.FromStation.GetHashCode();
                if (this.ToStation != null)
                    hashCode = hashCode * 59 + this.ToStation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
