/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TflApiPresentationEntitiesJourneyPlannerJourneyFare
    /// </summary>
    [DataContract]
    public partial class TflApiPresentationEntitiesJourneyPlannerJourneyFare :  IEquatable<TflApiPresentationEntitiesJourneyPlannerJourneyFare>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TflApiPresentationEntitiesJourneyPlannerJourneyFare" /> class.
        /// </summary>
        /// <param name="totalCost">totalCost.</param>
        /// <param name="fares">fares.</param>
        /// <param name="caveats">caveats.</param>
        public TflApiPresentationEntitiesJourneyPlannerJourneyFare(int? totalCost = default(int?), List<TflApiPresentationEntitiesJourneyPlannerFare> fares = default(List<TflApiPresentationEntitiesJourneyPlannerFare>), List<TflApiPresentationEntitiesJourneyPlannerFareCaveat> caveats = default(List<TflApiPresentationEntitiesJourneyPlannerFareCaveat>))
        {
            this.TotalCost = totalCost;
            this.Fares = fares;
            this.Caveats = caveats;
        }
        
        /// <summary>
        /// Gets or Sets TotalCost
        /// </summary>
        [DataMember(Name="totalCost", EmitDefaultValue=false)]
        public int? TotalCost { get; set; }

        /// <summary>
        /// Gets or Sets Fares
        /// </summary>
        [DataMember(Name="fares", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesJourneyPlannerFare> Fares { get; set; }

        /// <summary>
        /// Gets or Sets Caveats
        /// </summary>
        [DataMember(Name="caveats", EmitDefaultValue=false)]
        public List<TflApiPresentationEntitiesJourneyPlannerFareCaveat> Caveats { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TflApiPresentationEntitiesJourneyPlannerJourneyFare {\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("  Fares: ").Append(Fares).Append("\n");
            sb.Append("  Caveats: ").Append(Caveats).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TflApiPresentationEntitiesJourneyPlannerJourneyFare);
        }

        /// <summary>
        /// Returns true if TflApiPresentationEntitiesJourneyPlannerJourneyFare instances are equal
        /// </summary>
        /// <param name="input">Instance of TflApiPresentationEntitiesJourneyPlannerJourneyFare to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TflApiPresentationEntitiesJourneyPlannerJourneyFare input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TotalCost == input.TotalCost ||
                    (this.TotalCost != null &&
                    this.TotalCost.Equals(input.TotalCost))
                ) && 
                (
                    this.Fares == input.Fares ||
                    this.Fares != null &&
                    this.Fares.SequenceEqual(input.Fares)
                ) && 
                (
                    this.Caveats == input.Caveats ||
                    this.Caveats != null &&
                    this.Caveats.SequenceEqual(input.Caveats)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TotalCost != null)
                    hashCode = hashCode * 59 + this.TotalCost.GetHashCode();
                if (this.Fares != null)
                    hashCode = hashCode * 59 + this.Fares.GetHashCode();
                if (this.Caveats != null)
                    hashCode = hashCode * 59 + this.Caveats.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
