@startuml
interface IRoute {
}
class Station {
    + <<readonly>> Name : string
    + Station(name:string)
}
struct StationData {
    + Name : string
    + ID : int
    + Naptan : string
}
class TransportNetwork {
}
class Timetable {
}
@enduml
