@startuml
class SystemObject <<partial>> {
    + SystemObject()
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:SystemObject) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<SystemObject>" <|-- SystemObject
IValidatableObject <|-- SystemObject
@enduml
