@startuml
class TflApiPresentationEntitiesPoint <<partial>> {
    + TflApiPresentationEntitiesPoint(lat:double?, lon:double?)
    + Lat : double? <<get>> <<set>>
    + Lon : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesPoint) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesPoint>" <|-- TflApiPresentationEntitiesPoint
IValidatableObject <|-- TflApiPresentationEntitiesPoint
@enduml
