@startuml
class TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData(originNumberOfBikes:int?, destinationNumberOfBikes:int?, originNumberOfEmptySlots:int?, destinationNumberOfEmptySlots:int?, originId:string, destinationId:string)
    + OriginNumberOfBikes : int? <<get>> <<set>>
    + DestinationNumberOfBikes : int? <<get>> <<set>>
    + OriginNumberOfEmptySlots : int? <<get>> <<set>>
    + DestinationNumberOfEmptySlots : int? <<get>> <<set>>
    + OriginId : string <<get>> <<set>>
    + DestinationId : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData>" <|-- TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData
@enduml
