@startuml
class TflApiPresentationEntitiesStreet <<partial>> {
    + TflApiPresentationEntitiesStreet(name:string, closure:string, directions:string, segments:List<TflApiPresentationEntitiesStreetSegment>, sourceSystemId:long?, sourceSystemKey:string)
    + Name : string <<get>> <<set>>
    + Closure : string <<get>> <<set>>
    + Directions : string <<get>> <<set>>
    + SourceSystemId : long? <<get>> <<set>>
    + SourceSystemKey : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesStreet) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesStreet>" <|-- TflApiPresentationEntitiesStreet
IValidatableObject <|-- TflApiPresentationEntitiesStreet
TflApiPresentationEntitiesStreet --> "Segments<TflApiPresentationEntitiesStreetSegment>" "List`1"
@enduml
