@startuml
class TflApiPresentationEntitiesStatusSeverity <<partial>> {
    + TflApiPresentationEntitiesStatusSeverity(modeName:string, severityLevel:int?, description:string)
    + ModeName : string <<get>> <<set>>
    + SeverityLevel : int? <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesStatusSeverity) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesStatusSeverity>" <|-- TflApiPresentationEntitiesStatusSeverity
IValidatableObject <|-- TflApiPresentationEntitiesStatusSeverity
@enduml
