@startuml
class TflApiPresentationEntitiesFaresFaresPeriod <<partial>> {
    + TflApiPresentationEntitiesFaresFaresPeriod(id:int?, startDate:DateTime?, viewableDate:DateTime?, endDate:DateTime?, isFuture:bool?)
    + Id : int? <<get>> <<set>>
    + StartDate : DateTime? <<get>> <<set>>
    + ViewableDate : DateTime? <<get>> <<set>>
    + EndDate : DateTime? <<get>> <<set>>
    + IsFuture : bool? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresFaresPeriod) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresFaresPeriod>" <|-- TflApiPresentationEntitiesFaresFaresPeriod
IValidatableObject <|-- TflApiPresentationEntitiesFaresFaresPeriod
@enduml
