@startuml
class TflApiPresentationEntitiesFaresRecommendation <<partial>> {
    + TflApiPresentationEntitiesFaresRecommendation(id:int?, rule:int?, rank:int?, fareType:string, product:string, ticketType:string, ticketTime:string, productType:string, discountCard:string, zones:string, cost:string, priceDescription:string, priceComparison:string, recommendedTopUp:string, notes:List<TflApiPresentationEntitiesMessage>, keyFeatures:List<TflApiPresentationEntitiesMessage>, gettingYourTicket:List<TflApiPresentationEntitiesMessage>, singleFare:double?)
    + Id : int? <<get>> <<set>>
    + Rule : int? <<get>> <<set>>
    + Rank : int? <<get>> <<set>>
    + FareType : string <<get>> <<set>>
    + Product : string <<get>> <<set>>
    + TicketType : string <<get>> <<set>>
    + TicketTime : string <<get>> <<set>>
    + ProductType : string <<get>> <<set>>
    + DiscountCard : string <<get>> <<set>>
    + Zones : string <<get>> <<set>>
    + Cost : string <<get>> <<set>>
    + PriceDescription : string <<get>> <<set>>
    + PriceComparison : string <<get>> <<set>>
    + RecommendedTopUp : string <<get>> <<set>>
    + SingleFare : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresRecommendation) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresRecommendation>" <|-- TflApiPresentationEntitiesFaresRecommendation
IValidatableObject <|-- TflApiPresentationEntitiesFaresRecommendation
TflApiPresentationEntitiesFaresRecommendation --> "Notes<TflApiPresentationEntitiesMessage>" "List`1"
TflApiPresentationEntitiesFaresRecommendation --> "KeyFeatures<TflApiPresentationEntitiesMessage>" "List`1"
TflApiPresentationEntitiesFaresRecommendation --> "GettingYourTicket<TflApiPresentationEntitiesMessage>" "List`1"
@enduml
