@startuml
class TflApiPresentationEntitiesFaresTicketType <<partial>> {
    + TflApiPresentationEntitiesFaresTicketType(type:string, description:string)
    + Type : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresTicketType) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresTicketType>" <|-- TflApiPresentationEntitiesFaresTicketType
IValidatableObject <|-- TflApiPresentationEntitiesFaresTicketType
@enduml
