@startuml
class TflApiCommonDateRange <<partial>> {
    + TflApiCommonDateRange(startDate:DateTime?, endDate:DateTime?)
    + StartDate : DateTime? <<get>> <<set>>
    + EndDate : DateTime? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiCommonDateRange) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiCommonDateRange>" <|-- TflApiCommonDateRange
IValidatableObject <|-- TflApiCommonDateRange
@enduml
