@startuml
class TflApiPresentationEntitiesStopPointSequence <<partial>> {
    + ServiceType : ServiceTypeEnum? <<get>> <<set>>
    + TflApiPresentationEntitiesStopPointSequence(lineId:string, lineName:string, direction:string, branchId:int?, nextBranchIds:List<int?>, prevBranchIds:List<int?>, stopPoint:List<TflApiPresentationEntitiesMatchedStop>, serviceType:ServiceTypeEnum?)
    + LineId : string <<get>> <<set>>
    + LineName : string <<get>> <<set>>
    + Direction : string <<get>> <<set>>
    + BranchId : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesStopPointSequence) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
enum ServiceTypeEnum {
    Regular= 1,
    Night= 2,
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesStopPointSequence>" <|-- TflApiPresentationEntitiesStopPointSequence
IValidatableObject <|-- TflApiPresentationEntitiesStopPointSequence
TflApiPresentationEntitiesStopPointSequence --> "NextBranchIds<int?>" "List`1"
TflApiPresentationEntitiesStopPointSequence --> "PrevBranchIds<int?>" "List`1"
TflApiPresentationEntitiesStopPointSequence --> "StopPoint<TflApiPresentationEntitiesMatchedStop>" "List`1"
TflApiPresentationEntitiesStopPointSequence +-- ServiceTypeEnum
@enduml
