@startuml
class TflApiPresentationEntitiesFaresFare <<partial>> {
    + TflApiPresentationEntitiesFaresFare(id:int?, passengerType:string, validFrom:DateTime?, validUntil:DateTime?, ticketTime:string, ticketType:string, cost:string, cap:double?, description:string, zone:string, mode:string)
    + Id : int? <<get>> <<set>>
    + PassengerType : string <<get>> <<set>>
    + ValidFrom : DateTime? <<get>> <<set>>
    + ValidUntil : DateTime? <<get>> <<set>>
    + TicketTime : string <<get>> <<set>>
    + TicketType : string <<get>> <<set>>
    + Cost : string <<get>> <<set>>
    + Cap : double? <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Zone : string <<get>> <<set>>
    + Mode : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresFare) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresFare>" <|-- TflApiPresentationEntitiesFaresFare
IValidatableObject <|-- TflApiPresentationEntitiesFaresFare
@enduml
