@startuml
class TflApiPresentationEntitiesJourneyPlannerRouteOption <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerRouteOption(id:string, name:string, directions:List<string>, lineIdentifier:TflApiPresentationEntitiesIdentifier, direction:string)
    + Id : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Direction : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerRouteOption) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerRouteOption>" <|-- TflApiPresentationEntitiesJourneyPlannerRouteOption
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerRouteOption
TflApiPresentationEntitiesJourneyPlannerRouteOption --> "Directions<string>" "List`1"
TflApiPresentationEntitiesJourneyPlannerRouteOption --> "LineIdentifier" TflApiPresentationEntitiesIdentifier
@enduml
