@startuml
class TflApiPresentationEntitiesFaresFareBounds <<partial>> {
    + TflApiPresentationEntitiesFaresFareBounds(id:int?, from:string, to:string, via:string, routeCode:string, description:string, displayName:string, _operator:string, displayOrder:int?, isPopularFare:bool?, isPopularTravelCard:bool?, isTour:bool?, messages:List<TflApiPresentationEntitiesMessage>)
    + Id : int? <<get>> <<set>>
    + From : string <<get>> <<set>>
    + To : string <<get>> <<set>>
    + Via : string <<get>> <<set>>
    + RouteCode : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + DisplayName : string <<get>> <<set>>
    + Operator : string <<get>> <<set>>
    + DisplayOrder : int? <<get>> <<set>>
    + IsPopularFare : bool? <<get>> <<set>>
    + IsPopularTravelCard : bool? <<get>> <<set>>
    + IsTour : bool? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresFareBounds) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresFareBounds>" <|-- TflApiPresentationEntitiesFaresFareBounds
IValidatableObject <|-- TflApiPresentationEntitiesFaresFareBounds
TflApiPresentationEntitiesFaresFareBounds --> "Messages<TflApiPresentationEntitiesMessage>" "List`1"
@enduml
