@startuml
class TflApiPresentationEntitiesChargeConnectorOccupancy <<partial>> {
    + TflApiPresentationEntitiesChargeConnectorOccupancy(id:int?, sourceSystemPlaceId:string, status:string)
    + Id : int? <<get>> <<set>>
    + SourceSystemPlaceId : string <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesChargeConnectorOccupancy) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesChargeConnectorOccupancy>" <|-- TflApiPresentationEntitiesChargeConnectorOccupancy
IValidatableObject <|-- TflApiPresentationEntitiesChargeConnectorOccupancy
@enduml
