@startuml
class TflApiPresentationEntitiesLineModeGroup <<partial>> {
    + TflApiPresentationEntitiesLineModeGroup(modeName:string, lineIdentifier:List<string>)
    + ModeName : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesLineModeGroup) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesLineModeGroup>" <|-- TflApiPresentationEntitiesLineModeGroup
IValidatableObject <|-- TflApiPresentationEntitiesLineModeGroup
TflApiPresentationEntitiesLineModeGroup --> "LineIdentifier<string>" "List`1"
@enduml
