@startuml
class TflApiPresentationEntitiesRouteSearchResponse <<partial>> {
    + TflApiPresentationEntitiesRouteSearchResponse(input:string, searchMatches:List<TflApiPresentationEntitiesRouteSearchMatch>)
    + Input : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesRouteSearchResponse) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesRouteSearchResponse>" <|-- TflApiPresentationEntitiesRouteSearchResponse
IValidatableObject <|-- TflApiPresentationEntitiesRouteSearchResponse
TflApiPresentationEntitiesRouteSearchResponse --> "SearchMatches<TflApiPresentationEntitiesRouteSearchMatch>" "List`1"
@enduml
