@startuml
class TflApiPresentationEntitiesRoadDisruption <<partial>> {
    + TflApiPresentationEntitiesRoadDisruption(id:string, url:string, point:string, severity:string, ordinal:int?, category:string, subCategory:string, comments:string, currentUpdate:string, currentUpdateDateTime:DateTime?, corridorIds:List<string>, startDateTime:DateTime?, endDateTime:DateTime?, lastModifiedTime:DateTime?, levelOfInterest:string, location:string, status:string, geography:SystemDataSpatialDbGeography, geometry:SystemDataSpatialDbGeography, streets:List<TflApiPresentationEntitiesStreet>, isProvisional:bool?, hasClosures:bool?, linkText:string, linkUrl:string, roadProject:TflApiPresentationEntitiesRoadProject, publishStartDate:DateTime?, publishEndDate:DateTime?, timeFrame:string, roadDisruptionLines:List<TflApiPresentationEntitiesRoadDisruptionLine>, roadDisruptionImpactAreas:List<TflApiPresentationEntitiesRoadDisruptionImpactArea>, recurringSchedules:List<TflApiPresentationEntitiesRoadDisruptionSchedule>)
    + Id : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + Point : string <<get>> <<set>>
    + Severity : string <<get>> <<set>>
    + Ordinal : int? <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + SubCategory : string <<get>> <<set>>
    + Comments : string <<get>> <<set>>
    + CurrentUpdate : string <<get>> <<set>>
    + CurrentUpdateDateTime : DateTime? <<get>> <<set>>
    + StartDateTime : DateTime? <<get>> <<set>>
    + EndDateTime : DateTime? <<get>> <<set>>
    + LastModifiedTime : DateTime? <<get>> <<set>>
    + LevelOfInterest : string <<get>> <<set>>
    + Location : string <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + IsProvisional : bool? <<get>> <<set>>
    + HasClosures : bool? <<get>> <<set>>
    + LinkText : string <<get>> <<set>>
    + LinkUrl : string <<get>> <<set>>
    + PublishStartDate : DateTime? <<get>> <<set>>
    + PublishEndDate : DateTime? <<get>> <<set>>
    + TimeFrame : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesRoadDisruption) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesRoadDisruption>" <|-- TflApiPresentationEntitiesRoadDisruption
IValidatableObject <|-- TflApiPresentationEntitiesRoadDisruption
TflApiPresentationEntitiesRoadDisruption --> "CorridorIds<string>" "List`1"
TflApiPresentationEntitiesRoadDisruption --> "Geography" SystemDataSpatialDbGeography
TflApiPresentationEntitiesRoadDisruption --> "Geometry" SystemDataSpatialDbGeography
TflApiPresentationEntitiesRoadDisruption --> "Streets<TflApiPresentationEntitiesStreet>" "List`1"
TflApiPresentationEntitiesRoadDisruption --> "RoadProject" TflApiPresentationEntitiesRoadProject
TflApiPresentationEntitiesRoadDisruption --> "RoadDisruptionLines<TflApiPresentationEntitiesRoadDisruptionLine>" "List`1"
TflApiPresentationEntitiesRoadDisruption --> "RoadDisruptionImpactAreas<TflApiPresentationEntitiesRoadDisruptionImpactArea>" "List`1"
TflApiPresentationEntitiesRoadDisruption --> "RecurringSchedules<TflApiPresentationEntitiesRoadDisruptionSchedule>" "List`1"
@enduml
