@startuml
class TflApiPresentationEntitiesSearchResponse <<partial>> {
    + TflApiPresentationEntitiesSearchResponse(query:string, from:int?, page:int?, pageSize:int?, provider:string, total:int?, matches:List<TflApiPresentationEntitiesSearchMatch>, maxScore:double?)
    + Query : string <<get>> <<set>>
    + From : int? <<get>> <<set>>
    + Page : int? <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + Provider : string <<get>> <<set>>
    + Total : int? <<get>> <<set>>
    + MaxScore : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesSearchResponse) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesSearchResponse>" <|-- TflApiPresentationEntitiesSearchResponse
IValidatableObject <|-- TflApiPresentationEntitiesSearchResponse
TflApiPresentationEntitiesSearchResponse --> "Matches<TflApiPresentationEntitiesSearchMatch>" "List`1"
@enduml
