@startuml
class TflApiPresentationEntitiesFaresRecommendationResponse <<partial>> {
    + TflApiPresentationEntitiesFaresRecommendationResponse(recommendations:List<TflApiPresentationEntitiesFaresRecommendation>)
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresRecommendationResponse) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresRecommendationResponse>" <|-- TflApiPresentationEntitiesFaresRecommendationResponse
IValidatableObject <|-- TflApiPresentationEntitiesFaresRecommendationResponse
TflApiPresentationEntitiesFaresRecommendationResponse --> "Recommendations<TflApiPresentationEntitiesFaresRecommendation>" "List`1"
@enduml
