@startuml
class TflApiPresentationEntitiesMatchedRouteSections <<partial>> {
    + TflApiPresentationEntitiesMatchedRouteSections(id:int?)
    + Id : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesMatchedRouteSections) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesMatchedRouteSections>" <|-- TflApiPresentationEntitiesMatchedRouteSections
IValidatableObject <|-- TflApiPresentationEntitiesMatchedRouteSections
@enduml
