@startuml
class TflApiPresentationEntitiesLineSpecificServiceType <<partial>> {
    + TflApiPresentationEntitiesLineSpecificServiceType(serviceType:TflApiPresentationEntitiesLineServiceTypeInfo, stopServesServiceType:bool?)
    + StopServesServiceType : bool? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesLineSpecificServiceType) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesLineSpecificServiceType>" <|-- TflApiPresentationEntitiesLineSpecificServiceType
IValidatableObject <|-- TflApiPresentationEntitiesLineSpecificServiceType
TflApiPresentationEntitiesLineSpecificServiceType --> "ServiceType" TflApiPresentationEntitiesLineServiceTypeInfo
@enduml
