@startuml
class TflApiPresentationEntitiesRoadDisruptionLine <<partial>> {
    + TflApiPresentationEntitiesRoadDisruptionLine(id:int?, roadDisruptionId:string, isDiversion:bool?, multiLineString:SystemDataSpatialDbGeography, startDate:DateTime?, endDate:DateTime?, startTime:string, endTime:string)
    + Id : int? <<get>> <<set>>
    + RoadDisruptionId : string <<get>> <<set>>
    + IsDiversion : bool? <<get>> <<set>>
    + StartDate : DateTime? <<get>> <<set>>
    + EndDate : DateTime? <<get>> <<set>>
    + StartTime : string <<get>> <<set>>
    + EndTime : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesRoadDisruptionLine) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesRoadDisruptionLine>" <|-- TflApiPresentationEntitiesRoadDisruptionLine
IValidatableObject <|-- TflApiPresentationEntitiesRoadDisruptionLine
TflApiPresentationEntitiesRoadDisruptionLine --> "MultiLineString" SystemDataSpatialDbGeography
@enduml
