@startuml
class TflApiPresentationEntitiesDisruptedRoute <<partial>> {
    + TflApiPresentationEntitiesDisruptedRoute(id:string, lineId:string, routeCode:string, name:string, lineString:string, direction:string, originationName:string, destinationName:string, via:TflApiPresentationEntitiesRouteSectionNaptanEntrySequence, isEntireRouteSection:bool?, validTo:DateTime?, validFrom:DateTime?, routeSectionNaptanEntrySequence:List<TflApiPresentationEntitiesRouteSectionNaptanEntrySequence>)
    + Id : string <<get>> <<set>>
    + LineId : string <<get>> <<set>>
    + RouteCode : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + LineString : string <<get>> <<set>>
    + Direction : string <<get>> <<set>>
    + OriginationName : string <<get>> <<set>>
    + DestinationName : string <<get>> <<set>>
    + IsEntireRouteSection : bool? <<get>> <<set>>
    + ValidTo : DateTime? <<get>> <<set>>
    + ValidFrom : DateTime? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesDisruptedRoute) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesDisruptedRoute>" <|-- TflApiPresentationEntitiesDisruptedRoute
IValidatableObject <|-- TflApiPresentationEntitiesDisruptedRoute
TflApiPresentationEntitiesDisruptedRoute --> "Via" TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
TflApiPresentationEntitiesDisruptedRoute --> "RouteSectionNaptanEntrySequence<TflApiPresentationEntitiesRouteSectionNaptanEntrySequence>" "List`1"
@enduml
