@startuml
class TflApiPresentationEntitiesRoadProject <<partial>> {
    + Phase : PhaseEnum? <<get>> <<set>>
    + TflApiPresentationEntitiesRoadProject(projectId:string, schemeName:string, projectName:string, projectDescription:string, projectPageUrl:string, consultationPageUrl:string, consultationStartDate:DateTime?, consultationEndDate:DateTime?, constructionStartDate:DateTime?, constructionEndDate:DateTime?, boroughsBenefited:List<string>, cycleSuperhighwayId:string, phase:PhaseEnum?, contactName:string, contactEmail:string, externalPageUrl:string, projectSummaryPageUrl:string)
    + ProjectId : string <<get>> <<set>>
    + SchemeName : string <<get>> <<set>>
    + ProjectName : string <<get>> <<set>>
    + ProjectDescription : string <<get>> <<set>>
    + ProjectPageUrl : string <<get>> <<set>>
    + ConsultationPageUrl : string <<get>> <<set>>
    + ConsultationStartDate : DateTime? <<get>> <<set>>
    + ConsultationEndDate : DateTime? <<get>> <<set>>
    + ConstructionStartDate : DateTime? <<get>> <<set>>
    + ConstructionEndDate : DateTime? <<get>> <<set>>
    + CycleSuperhighwayId : string <<get>> <<set>>
    + ContactName : string <<get>> <<set>>
    + ContactEmail : string <<get>> <<set>>
    + ExternalPageUrl : string <<get>> <<set>>
    + ProjectSummaryPageUrl : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesRoadProject) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
enum PhaseEnum {
    Unscoped= 1,
    Concept= 2,
    ConsultationEnded= 3,
    Consultation= 4,
    Construction= 5,
    Complete= 6,
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesRoadProject>" <|-- TflApiPresentationEntitiesRoadProject
IValidatableObject <|-- TflApiPresentationEntitiesRoadProject
TflApiPresentationEntitiesRoadProject --> "BoroughsBenefited<string>" "List`1"
TflApiPresentationEntitiesRoadProject +-- PhaseEnum
@enduml
