@startuml
class TflApiPresentationEntitiesInterval <<partial>> {
    + TflApiPresentationEntitiesInterval(stopId:string, timeToArrival:double?)
    + StopId : string <<get>> <<set>>
    + TimeToArrival : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesInterval) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesInterval>" <|-- TflApiPresentationEntitiesInterval
IValidatableObject <|-- TflApiPresentationEntitiesInterval
@enduml
