@startuml
class TflApiPresentationEntitiesJourneyPlannerTimeAdjustment <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerTimeAdjustment(date:string, time:string, timeIs:string, uri:string)
    + Date : string <<get>> <<set>>
    + Time : string <<get>> <<set>>
    + TimeIs : string <<get>> <<set>>
    + Uri : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerTimeAdjustment) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerTimeAdjustment>" <|-- TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
@enduml
