@startuml
class TflApiPresentationEntitiesTrainLoading <<partial>> {
    + TflApiPresentationEntitiesTrainLoading(line:string, lineDirection:string, platformDirection:string, direction:string, naptanTo:string, timeSlice:string, value:int?)
    + Line : string <<get>> <<set>>
    + LineDirection : string <<get>> <<set>>
    + PlatformDirection : string <<get>> <<set>>
    + Direction : string <<get>> <<set>>
    + NaptanTo : string <<get>> <<set>>
    + TimeSlice : string <<get>> <<set>>
    + Value : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesTrainLoading) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesTrainLoading>" <|-- TflApiPresentationEntitiesTrainLoading
IValidatableObject <|-- TflApiPresentationEntitiesTrainLoading
@enduml
