@startuml
class TflApiCommonApiVersionInfo <<partial>> {
    + TflApiCommonApiVersionInfo(label:string, timestamp:DateTime?, version:string, assemblies:List<string>)
    + Label : string <<get>> <<set>>
    + Timestamp : DateTime? <<get>> <<set>>
    + Version : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiCommonApiVersionInfo) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiCommonApiVersionInfo>" <|-- TflApiCommonApiVersionInfo
IValidatableObject <|-- TflApiCommonApiVersionInfo
TflApiCommonApiVersionInfo --> "Assemblies<string>" "List`1"
@enduml
