@startuml
class TflApiPresentationEntitiesFaresPassengerType <<partial>> {
    + TflApiPresentationEntitiesFaresPassengerType(type:string, description:string, displayName:string, displayOrder:int?)
    + Type : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + DisplayName : string <<get>> <<set>>
    + DisplayOrder : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresPassengerType) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresPassengerType>" <|-- TflApiPresentationEntitiesFaresPassengerType
IValidatableObject <|-- TflApiPresentationEntitiesFaresPassengerType
@enduml
