@startuml
class TflApiPresentationEntitiesTwentyFourHourClockTime <<partial>> {
    + TflApiPresentationEntitiesTwentyFourHourClockTime(hour:string, minute:string)
    + Hour : string <<get>> <<set>>
    + Minute : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesTwentyFourHourClockTime) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesTwentyFourHourClockTime>" <|-- TflApiPresentationEntitiesTwentyFourHourClockTime
IValidatableObject <|-- TflApiPresentationEntitiesTwentyFourHourClockTime
@enduml
