@startuml
class TflApiPresentationEntitiesTimetablesDisambiguationOption <<partial>> {
    + TflApiPresentationEntitiesTimetablesDisambiguationOption(description:string, uri:string)
    + Description : string <<get>> <<set>>
    + Uri : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesTimetablesDisambiguationOption) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesTimetablesDisambiguationOption>" <|-- TflApiPresentationEntitiesTimetablesDisambiguationOption
IValidatableObject <|-- TflApiPresentationEntitiesTimetablesDisambiguationOption
@enduml
