@startuml
class TflApiPresentationEntitiesInstruction <<partial>> {
    + TflApiPresentationEntitiesInstruction(summary:string, detailed:string, steps:List<TflApiPresentationEntitiesInstructionStep>)
    + Summary : string <<get>> <<set>>
    + Detailed : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesInstruction) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesInstruction>" <|-- TflApiPresentationEntitiesInstruction
IValidatableObject <|-- TflApiPresentationEntitiesInstruction
TflApiPresentationEntitiesInstruction --> "Steps<TflApiPresentationEntitiesInstructionStep>" "List`1"
@enduml
