@startuml
class TflApiPresentationEntitiesAccidentStatsVehicle <<partial>> {
    + TflApiPresentationEntitiesAccidentStatsVehicle(type:string)
    + Type : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesAccidentStatsVehicle) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesAccidentStatsVehicle>" <|-- TflApiPresentationEntitiesAccidentStatsVehicle
IValidatableObject <|-- TflApiPresentationEntitiesAccidentStatsVehicle
@enduml
