@startuml
class TflApiCommonPostcodeInput <<partial>> {
    + TflApiCommonPostcodeInput(postcode:string)
    + Postcode : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiCommonPostcodeInput) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiCommonPostcodeInput>" <|-- TflApiCommonPostcodeInput
IValidatableObject <|-- TflApiCommonPostcodeInput
@enduml
