@startuml
class TflApiPresentationEntitiesRoadDisruptionSchedule <<partial>> {
    + TflApiPresentationEntitiesRoadDisruptionSchedule(startTime:DateTime?, endTime:DateTime?)
    + StartTime : DateTime? <<get>> <<set>>
    + EndTime : DateTime? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesRoadDisruptionSchedule) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesRoadDisruptionSchedule>" <|-- TflApiPresentationEntitiesRoadDisruptionSchedule
IValidatableObject <|-- TflApiPresentationEntitiesRoadDisruptionSchedule
@enduml
