@startuml
class TflApiCommonPlaceGeo <<partial>> {
    + TflApiCommonPlaceGeo(swLat:double?, swLon:double?, neLat:double?, neLon:double?, lat:double?, lon:double?)
    + SwLat : double? <<get>> <<set>>
    + SwLon : double? <<get>> <<set>>
    + NeLat : double? <<get>> <<set>>
    + NeLon : double? <<get>> <<set>>
    + Lat : double? <<get>> <<set>>
    + Lon : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiCommonPlaceGeo) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiCommonPlaceGeo>" <|-- TflApiCommonPlaceGeo
IValidatableObject <|-- TflApiCommonPlaceGeo
@enduml
