@startuml
class TflApiPresentationEntitiesCrowding <<partial>> {
    + TflApiPresentationEntitiesCrowding(passengerFlows:List<TflApiPresentationEntitiesPassengerFlow>, trainLoadings:List<TflApiPresentationEntitiesTrainLoading>)
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesCrowding) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesCrowding>" <|-- TflApiPresentationEntitiesCrowding
IValidatableObject <|-- TflApiPresentationEntitiesCrowding
TflApiPresentationEntitiesCrowding --> "PassengerFlows<TflApiPresentationEntitiesPassengerFlow>" "List`1"
TflApiPresentationEntitiesCrowding --> "TrainLoadings<TflApiPresentationEntitiesTrainLoading>" "List`1"
@enduml
