@startuml
class TflApiCommonGeoPoint <<partial>> {
    + TflApiCommonGeoPoint(lat:double?, lon:double?)
    + Lat : double? <<get>> <<set>>
    + Lon : double? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiCommonGeoPoint) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiCommonGeoPoint>" <|-- TflApiCommonGeoPoint
IValidatableObject <|-- TflApiCommonGeoPoint
@enduml
