@startuml
class TflApiPresentationEntitiesLineServiceType <<partial>> {
    + TflApiPresentationEntitiesLineServiceType(lineName:string, lineSpecificServiceTypes:List<TflApiPresentationEntitiesLineSpecificServiceType>)
    + LineName : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesLineServiceType) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesLineServiceType>" <|-- TflApiPresentationEntitiesLineServiceType
IValidatableObject <|-- TflApiPresentationEntitiesLineServiceType
TflApiPresentationEntitiesLineServiceType --> "LineSpecificServiceTypes<TflApiPresentationEntitiesLineSpecificServiceType>" "List`1"
@enduml
