@startuml
class TflApiPresentationEntitiesJourneyPlannerFareTap <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerFareTap(atcoCode:string, tapDetails:TflApiPresentationEntitiesJourneyPlannerFareTapDetails)
    + AtcoCode : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerFareTap) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerFareTap>" <|-- TflApiPresentationEntitiesJourneyPlannerFareTap
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerFareTap
TflApiPresentationEntitiesJourneyPlannerFareTap --> "TapDetails" TflApiPresentationEntitiesJourneyPlannerFareTapDetails
@enduml
