@startuml
class TflApiPresentationEntitiesJourneyPlannerFareTapDetails <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerFareTapDetails(modeType:string, validationType:string, hostDeviceType:string, busRouteId:string, nationalLocationCode:int?, tapTimestamp:DateTime?)
    + ModeType : string <<get>> <<set>>
    + ValidationType : string <<get>> <<set>>
    + HostDeviceType : string <<get>> <<set>>
    + BusRouteId : string <<get>> <<set>>
    + NationalLocationCode : int? <<get>> <<set>>
    + TapTimestamp : DateTime? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerFareTapDetails) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerFareTapDetails>" <|-- TflApiPresentationEntitiesJourneyPlannerFareTapDetails
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerFareTapDetails
@enduml
