@startuml
class TflApiPresentationEntitiesFaresFaresSection <<partial>> {
    + TflApiPresentationEntitiesFaresFaresSection(header:string, index:int?, journey:TflApiPresentationEntitiesFaresJourney, rows:List<TflApiPresentationEntitiesFaresFareDetails>, messages:List<TflApiPresentationEntitiesMessage>)
    + Header : string <<get>> <<set>>
    + Index : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresFaresSection) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresFaresSection>" <|-- TflApiPresentationEntitiesFaresFaresSection
IValidatableObject <|-- TflApiPresentationEntitiesFaresFaresSection
TflApiPresentationEntitiesFaresFaresSection --> "Journey" TflApiPresentationEntitiesFaresJourney
TflApiPresentationEntitiesFaresFaresSection --> "Rows<TflApiPresentationEntitiesFaresFareDetails>" "List`1"
TflApiPresentationEntitiesFaresFaresSection --> "Messages<TflApiPresentationEntitiesMessage>" "List`1"
@enduml
