@startuml
class TflApiPresentationEntitiesCoordinate <<partial>> {
    + TflApiPresentationEntitiesCoordinate(longitude:double?, latitude:double?, easting:double?, northing:double?, xCoord:int?, yCoord:int?)
    + Longitude : double? <<get>> <<set>>
    + Latitude : double? <<get>> <<set>>
    + Easting : double? <<get>> <<set>>
    + Northing : double? <<get>> <<set>>
    + XCoord : int? <<get>> <<set>>
    + YCoord : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesCoordinate) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesCoordinate>" <|-- TflApiPresentationEntitiesCoordinate
IValidatableObject <|-- TflApiPresentationEntitiesCoordinate
@enduml
