@startuml
class TflApiPresentationEntitiesLineRouteSection <<partial>> {
    + TflApiPresentationEntitiesLineRouteSection(routeId:int?, direction:string, destination:string, fromStation:string, toStation:string, serviceType:string, vehicleDestinationText:string)
    + RouteId : int? <<get>> <<set>>
    + Direction : string <<get>> <<set>>
    + Destination : string <<get>> <<set>>
    + FromStation : string <<get>> <<set>>
    + ToStation : string <<get>> <<set>>
    + ServiceType : string <<get>> <<set>>
    + VehicleDestinationText : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesLineRouteSection) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesLineRouteSection>" <|-- TflApiPresentationEntitiesLineRouteSection
IValidatableObject <|-- TflApiPresentationEntitiesLineRouteSection
@enduml
