@startuml
class TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary <<partial>> {
    + TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary(year:int?, borough:string, accidents:int?)
    + Year : int? <<get>> <<set>>
    + Borough : string <<get>> <<set>>
    + Accidents : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary>" <|-- TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary
IValidatableObject <|-- TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary
@enduml
