@startuml
class TflApiPresentationEntitiesFaresFareStation <<partial>> {
    + FareCategory : FareCategoryEnum? <<get>> <<set>>
    + TflApiPresentationEntitiesFaresFareStation(atcoCode:string, commonName:string, fareCategory:FareCategoryEnum?)
    + AtcoCode : string <<get>> <<set>>
    + CommonName : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesFaresFareStation) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
enum FareCategoryEnum {
    Cash= 1,
    Oyster= 2,
    Contactless= 3,
    ContactlessOnly= 4,
    All= 5,
}
"IEquatable`1" "<TflApiPresentationEntitiesFaresFareStation>" <|-- TflApiPresentationEntitiesFaresFareStation
IValidatableObject <|-- TflApiPresentationEntitiesFaresFareStation
TflApiPresentationEntitiesFaresFareStation +-- FareCategoryEnum
@enduml
