@startuml
class TflApiPresentationEntitiesPlaceCategory <<partial>> {
    + TflApiPresentationEntitiesPlaceCategory(category:string, availableKeys:List<string>)
    + Category : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesPlaceCategory) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesPlaceCategory>" <|-- TflApiPresentationEntitiesPlaceCategory
IValidatableObject <|-- TflApiPresentationEntitiesPlaceCategory
TflApiPresentationEntitiesPlaceCategory --> "AvailableKeys<string>" "List`1"
@enduml
