@startuml
class TflApiPresentationEntitiesStreetSegment <<partial>> {
    + TflApiPresentationEntitiesStreetSegment(toid:string, lineString:string, sourceSystemId:long?, sourceSystemKey:string)
    + Toid : string <<get>> <<set>>
    + LineString : string <<get>> <<set>>
    + SourceSystemId : long? <<get>> <<set>>
    + SourceSystemKey : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesStreetSegment) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesStreetSegment>" <|-- TflApiPresentationEntitiesStreetSegment
IValidatableObject <|-- TflApiPresentationEntitiesStreetSegment
@enduml
