@startuml
class TflApiPresentationEntitiesJourneyPlannerLeg <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerLeg(duration:int?, speed:string, instruction:TflApiPresentationEntitiesInstruction, obstacles:List<TflApiPresentationEntitiesJourneyPlannerObstacle>, departureTime:DateTime?, arrivalTime:DateTime?, departurePoint:TflApiPresentationEntitiesPoint, arrivalPoint:TflApiPresentationEntitiesPoint, path:TflApiPresentationEntitiesJourneyPlannerPath, routeOptions:List<TflApiPresentationEntitiesJourneyPlannerRouteOption>, mode:TflApiPresentationEntitiesIdentifier, disruptions:List<TflApiPresentationEntitiesDisruption>, plannedWorks:List<TflApiPresentationEntitiesJourneyPlannerPlannedWork>, distance:double?, scheduledDepartureTime:DateTime?, scheduledArrivalTime:DateTime?, interChangeDuration:string, interChangePosition:string)
    + Duration : int? <<get>> <<set>>
    + Speed : string <<get>> <<set>>
    + DepartureTime : DateTime? <<get>> <<set>>
    + ArrivalTime : DateTime? <<get>> <<set>>
    + Distance : double? <<get>> <<set>>
    + IsDisrupted : bool? <<get>>
    + HasFixedLocations : bool? <<get>>
    + ScheduledDepartureTime : DateTime? <<get>> <<set>>
    + ScheduledArrivalTime : DateTime? <<get>> <<set>>
    + InterChangeDuration : string <<get>> <<set>>
    + InterChangePosition : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerLeg) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerLeg>" <|-- TflApiPresentationEntitiesJourneyPlannerLeg
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerLeg
TflApiPresentationEntitiesJourneyPlannerLeg --> "Instruction" TflApiPresentationEntitiesInstruction
TflApiPresentationEntitiesJourneyPlannerLeg --> "Obstacles<TflApiPresentationEntitiesJourneyPlannerObstacle>" "List`1"
TflApiPresentationEntitiesJourneyPlannerLeg --> "DeparturePoint" TflApiPresentationEntitiesPoint
TflApiPresentationEntitiesJourneyPlannerLeg --> "ArrivalPoint" TflApiPresentationEntitiesPoint
TflApiPresentationEntitiesJourneyPlannerLeg --> "Path" TflApiPresentationEntitiesJourneyPlannerPath
TflApiPresentationEntitiesJourneyPlannerLeg --> "RouteOptions<TflApiPresentationEntitiesJourneyPlannerRouteOption>" "List`1"
TflApiPresentationEntitiesJourneyPlannerLeg --> "Mode" TflApiPresentationEntitiesIdentifier
TflApiPresentationEntitiesJourneyPlannerLeg --> "Disruptions<TflApiPresentationEntitiesDisruption>" "List`1"
TflApiPresentationEntitiesJourneyPlannerLeg --> "PlannedWorks<TflApiPresentationEntitiesJourneyPlannerPlannedWork>" "List`1"
@enduml
