@startuml
class TflApiPresentationEntitiesAccidentStatsAccidentDetail <<partial>> {
    + TflApiPresentationEntitiesAccidentStatsAccidentDetail(id:int?, lat:double?, lon:double?, location:string, date:DateTime?, severity:string, borough:string, casualties:List<TflApiPresentationEntitiesAccidentStatsCasualty>, vehicles:List<TflApiPresentationEntitiesAccidentStatsVehicle>)
    + Id : int? <<get>> <<set>>
    + Lat : double? <<get>> <<set>>
    + Lon : double? <<get>> <<set>>
    + Location : string <<get>> <<set>>
    + Date : DateTime? <<get>> <<set>>
    + Severity : string <<get>> <<set>>
    + Borough : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesAccidentStatsAccidentDetail) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesAccidentStatsAccidentDetail>" <|-- TflApiPresentationEntitiesAccidentStatsAccidentDetail
IValidatableObject <|-- TflApiPresentationEntitiesAccidentStatsAccidentDetail
TflApiPresentationEntitiesAccidentStatsAccidentDetail --> "Casualties<TflApiPresentationEntitiesAccidentStatsCasualty>" "List`1"
TflApiPresentationEntitiesAccidentStatsAccidentDetail --> "Vehicles<TflApiPresentationEntitiesAccidentStatsVehicle>" "List`1"
@enduml
