@startuml
class TflApiPresentationEntitiesValidityPeriod <<partial>> {
    + TflApiPresentationEntitiesValidityPeriod(fromDate:DateTime?, toDate:DateTime?, isNow:bool?)
    + FromDate : DateTime? <<get>> <<set>>
    + ToDate : DateTime? <<get>> <<set>>
    + IsNow : bool? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesValidityPeriod) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesValidityPeriod>" <|-- TflApiPresentationEntitiesValidityPeriod
IValidatableObject <|-- TflApiPresentationEntitiesValidityPeriod
@enduml
