@startuml
class TflApiPresentationEntitiesMessage <<partial>> {
    + TflApiPresentationEntitiesMessage(bulletOrder:int?, header:bool?, messageText:string, linkText:string, url:string)
    + BulletOrder : int? <<get>> <<set>>
    + Header : bool? <<get>> <<set>>
    + MessageText : string <<get>> <<set>>
    + LinkText : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesMessage) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesMessage>" <|-- TflApiPresentationEntitiesMessage
IValidatableObject <|-- TflApiPresentationEntitiesMessage
@enduml
