@startuml
class TflApiPresentationEntitiesJourneyPlannerJourneyVector <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerJourneyVector(from:string, to:string, via:string, uri:string)
    + From : string <<get>> <<set>>
    + To : string <<get>> <<set>>
    + Via : string <<get>> <<set>>
    + Uri : string <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerJourneyVector) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerJourneyVector>" <|-- TflApiPresentationEntitiesJourneyPlannerJourneyVector
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerJourneyVector
@enduml
