@startuml
class TflApiPresentationEntitiesJourneyPlannerFare <<partial>> {
    + TflApiPresentationEntitiesJourneyPlannerFare(lowZone:int?, highZone:int?, cost:int?, chargeProfileName:string, isHopperFare:bool?, chargeLevel:string, peak:int?, offPeak:int?, taps:List<TflApiPresentationEntitiesJourneyPlannerFareTap>)
    + LowZone : int? <<get>> <<set>>
    + HighZone : int? <<get>> <<set>>
    + Cost : int? <<get>> <<set>>
    + ChargeProfileName : string <<get>> <<set>>
    + IsHopperFare : bool? <<get>> <<set>>
    + ChargeLevel : string <<get>> <<set>>
    + Peak : int? <<get>> <<set>>
    + OffPeak : int? <<get>> <<set>>
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesJourneyPlannerFare) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesJourneyPlannerFare>" <|-- TflApiPresentationEntitiesJourneyPlannerFare
IValidatableObject <|-- TflApiPresentationEntitiesJourneyPlannerFare
TflApiPresentationEntitiesJourneyPlannerFare --> "Taps<TflApiPresentationEntitiesJourneyPlannerFareTap>" "List`1"
@enduml
