@startuml
class TflApiPresentationEntitiesTimetableRoute <<partial>> {
    + TflApiPresentationEntitiesTimetableRoute(stationIntervals:List<TflApiPresentationEntitiesStationInterval>, schedules:List<TflApiPresentationEntitiesSchedule>)
    + <<override>> ToString() : string
    + <<virtual>> ToJson() : string
    + <<override>> Equals(input:object) : bool
    + Equals(input:TflApiPresentationEntitiesTimetableRoute) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<TflApiPresentationEntitiesTimetableRoute>" <|-- TflApiPresentationEntitiesTimetableRoute
IValidatableObject <|-- TflApiPresentationEntitiesTimetableRoute
TflApiPresentationEntitiesTimetableRoute --> "StationIntervals<TflApiPresentationEntitiesStationInterval>" "List`1"
TflApiPresentationEntitiesTimetableRoute --> "Schedules<TflApiPresentationEntitiesSchedule>" "List`1"
@enduml
