@startuml
class LineApiTests {
    + Init() : void
    + Cleanup() : void
    + InstanceTest() : void
    + LineArrivalsTest() : void
    + LineDisruptionTest() : void
    + LineDisruptionByModeTest() : void
    + LineGetTest() : void
    + LineGetByModeTest() : void
    + LineLineRoutesByIdsTest() : void
    + LineMetaDisruptionCategoriesTest() : void
    + LineMetaModesTest() : void
    + LineMetaServiceTypesTest() : void
    + LineMetaSeverityTest() : void
    + LineRouteTest() : void
    + LineRouteByModeTest() : void
    + LineRouteSequenceTest() : void
    + LineSearchTest() : void
    + LineStatusTest() : void
    + LineStatusByIdsTest() : void
    + LineStatusByModeTest() : void
    + LineStatusBySeverityTest() : void
    + LineStopPointsTest() : void
    + LineTimetableTest() : void
    + LineTimetableToTest() : void
}
@enduml
