@startuml
class PlaceApiTests {
    + Init() : void
    + Cleanup() : void
    + InstanceTest() : void
    + PlaceGetTest() : void
    + PlaceGetAtTest() : void
    + PlaceGetByGeoTest() : void
    + PlaceGetByTypeTest() : void
    + PlaceGetOverlayTest() : void
    + PlaceGetStreetsByPostCodeTest() : void
    + PlaceMetaCategoriesTest() : void
    + PlaceMetaPlaceTypesTest() : void
    + PlaceSearchTest() : void
}
@enduml
