@startuml
class StopPointApiTests {
    + Init() : void
    + Cleanup() : void
    + InstanceTest() : void
    + StopPointArrivalDeparturesTest() : void
    + StopPointArrivalsTest() : void
    + StopPointCrowdingTest() : void
    + StopPointDirectionTest() : void
    + StopPointDisruptionTest() : void
    + StopPointDisruptionByModeTest() : void
    + StopPointGetTest() : void
    + StopPointGetByGeoPointTest() : void
    + StopPointGetByModeTest() : void
    + StopPointGetBySmsTest() : void
    + StopPointGetByTypeTest() : void
    + StopPointGetByTypeWithPaginationTest() : void
    + StopPointGetCarParksByIdTest() : void
    + StopPointGetIdTest() : void
    + StopPointGetServiceTypesTest() : void
    + StopPointGetTaxiRanksByIdsTest() : void
    + StopPointMetaCategoriesTest() : void
    + StopPointMetaModesTest() : void
    + StopPointMetaStopTypesTest() : void
    + StopPointReachableFromTest() : void
    + StopPointRouteTest() : void
    + StopPointSearchTest() : void
    + StopPointSearch_0Test() : void
}
@enduml
