@startuml
class TravelTimeApiTests {
    + Init() : void
    + Cleanup() : void
    + InstanceTest() : void
    + TravelTimeGetCompareOverlayTest() : void
    + TravelTimeGetOverlayTest() : void
}
@enduml
