@startuml
class ApiException {
    + ErrorCode : int <<get>> <<set>>
    + ApiException()
    + ApiException(errorCode:int, message:string)
    + ApiException(errorCode:int, message:string, errorContent:dynamic)
}
Exception <|-- ApiException
ApiException --> "ErrorContent" dynamic
@enduml
