@startuml
class "ApiResponse`1"<T> {
    + StatusCode : int <<get>>
    + Data : T <<get>>
    + ApiResponse(statusCode:int, headers:IDictionary<string, string>, data:T)
}
class "IDictionary`2"<T1,T2> {
}
"ApiResponse`1" --> "Headers<string,string>" "IDictionary`2"
@enduml
