/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesCycleSuperhighway
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesCycleSuperhighwayTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesCycleSuperhighway
        //private TflApiPresentationEntitiesCycleSuperhighway instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesCycleSuperhighway
            //instance = new TflApiPresentationEntitiesCycleSuperhighway();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesCycleSuperhighway
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesCycleSuperhighwayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesCycleSuperhighway
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesCycleSuperhighway> (instance, "variable 'instance' is a TflApiPresentationEntitiesCycleSuperhighway");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'LabelShort'
        /// </summary>
        [Test]
        public void LabelShortTest()
        {
            // TODO unit test for the property 'LabelShort'
        }
        /// <summary>
        /// Test the property 'Geography'
        /// </summary>
        [Test]
        public void GeographyTest()
        {
            // TODO unit test for the property 'Geography'
        }
        /// <summary>
        /// Test the property 'Segmented'
        /// </summary>
        [Test]
        public void SegmentedTest()
        {
            // TODO unit test for the property 'Segmented'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'RouteType'
        /// </summary>
        [Test]
        public void RouteTypeTest()
        {
            // TODO unit test for the property 'RouteType'
        }

    }

}
