/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesDisruption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesDisruptionTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesDisruption
        //private TflApiPresentationEntitiesDisruption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesDisruption
            //instance = new TflApiPresentationEntitiesDisruption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesDisruption
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesDisruptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesDisruption
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesDisruption> (instance, "variable 'instance' is a TflApiPresentationEntitiesDisruption");
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Test]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Test]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Test]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'AffectedRoutes'
        /// </summary>
        [Test]
        public void AffectedRoutesTest()
        {
            // TODO unit test for the property 'AffectedRoutes'
        }
        /// <summary>
        /// Test the property 'AffectedStops'
        /// </summary>
        [Test]
        public void AffectedStopsTest()
        {
            // TODO unit test for the property 'AffectedStops'
        }
        /// <summary>
        /// Test the property 'ClosureText'
        /// </summary>
        [Test]
        public void ClosureTextTest()
        {
            // TODO unit test for the property 'ClosureText'
        }

    }

}
