/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesFaresTicketType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesFaresTicketTypeTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesFaresTicketType
        //private TflApiPresentationEntitiesFaresTicketType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesFaresTicketType
            //instance = new TflApiPresentationEntitiesFaresTicketType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesFaresTicketType
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesFaresTicketTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesFaresTicketType
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesFaresTicketType> (instance, "variable 'instance' is a TflApiPresentationEntitiesFaresTicketType");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
