/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesRoadDisruptionImpactArea
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesRoadDisruptionImpactAreaTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesRoadDisruptionImpactArea
        //private TflApiPresentationEntitiesRoadDisruptionImpactArea instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesRoadDisruptionImpactArea
            //instance = new TflApiPresentationEntitiesRoadDisruptionImpactArea();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesRoadDisruptionImpactArea
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesRoadDisruptionImpactAreaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesRoadDisruptionImpactArea
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesRoadDisruptionImpactArea> (instance, "variable 'instance' is a TflApiPresentationEntitiesRoadDisruptionImpactArea");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RoadDisruptionId'
        /// </summary>
        [Test]
        public void RoadDisruptionIdTest()
        {
            // TODO unit test for the property 'RoadDisruptionId'
        }
        /// <summary>
        /// Test the property 'Polygon'
        /// </summary>
        [Test]
        public void PolygonTest()
        {
            // TODO unit test for the property 'Polygon'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

    }

}
