/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesActiveServiceType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesActiveServiceTypeTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesActiveServiceType
        //private TflApiPresentationEntitiesActiveServiceType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesActiveServiceType
            //instance = new TflApiPresentationEntitiesActiveServiceType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesActiveServiceType
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesActiveServiceTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesActiveServiceType
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesActiveServiceType> (instance, "variable 'instance' is a TflApiPresentationEntitiesActiveServiceType");
        }


        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'ServiceType'
        /// </summary>
        [Test]
        public void ServiceTypeTest()
        {
            // TODO unit test for the property 'ServiceType'
        }

    }

}
