/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesScheduleTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesSchedule
        //private TflApiPresentationEntitiesSchedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesSchedule
            //instance = new TflApiPresentationEntitiesSchedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesSchedule
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesSchedule
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesSchedule> (instance, "variable 'instance' is a TflApiPresentationEntitiesSchedule");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'KnownJourneys'
        /// </summary>
        [Test]
        public void KnownJourneysTest()
        {
            // TODO unit test for the property 'KnownJourneys'
        }
        /// <summary>
        /// Test the property 'FirstJourney'
        /// </summary>
        [Test]
        public void FirstJourneyTest()
        {
            // TODO unit test for the property 'FirstJourney'
        }
        /// <summary>
        /// Test the property 'LastJourney'
        /// </summary>
        [Test]
        public void LastJourneyTest()
        {
            // TODO unit test for the property 'LastJourney'
        }
        /// <summary>
        /// Test the property 'Periods'
        /// </summary>
        [Test]
        public void PeriodsTest()
        {
            // TODO unit test for the property 'Periods'
        }

    }

}
