/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesDisruptedRoute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesDisruptedRouteTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesDisruptedRoute
        //private TflApiPresentationEntitiesDisruptedRoute instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesDisruptedRoute
            //instance = new TflApiPresentationEntitiesDisruptedRoute();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesDisruptedRoute
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesDisruptedRouteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesDisruptedRoute
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesDisruptedRoute> (instance, "variable 'instance' is a TflApiPresentationEntitiesDisruptedRoute");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'RouteCode'
        /// </summary>
        [Test]
        public void RouteCodeTest()
        {
            // TODO unit test for the property 'RouteCode'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LineString'
        /// </summary>
        [Test]
        public void LineStringTest()
        {
            // TODO unit test for the property 'LineString'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'OriginationName'
        /// </summary>
        [Test]
        public void OriginationNameTest()
        {
            // TODO unit test for the property 'OriginationName'
        }
        /// <summary>
        /// Test the property 'DestinationName'
        /// </summary>
        [Test]
        public void DestinationNameTest()
        {
            // TODO unit test for the property 'DestinationName'
        }
        /// <summary>
        /// Test the property 'Via'
        /// </summary>
        [Test]
        public void ViaTest()
        {
            // TODO unit test for the property 'Via'
        }
        /// <summary>
        /// Test the property 'IsEntireRouteSection'
        /// </summary>
        [Test]
        public void IsEntireRouteSectionTest()
        {
            // TODO unit test for the property 'IsEntireRouteSection'
        }
        /// <summary>
        /// Test the property 'ValidTo'
        /// </summary>
        [Test]
        public void ValidToTest()
        {
            // TODO unit test for the property 'ValidTo'
        }
        /// <summary>
        /// Test the property 'ValidFrom'
        /// </summary>
        [Test]
        public void ValidFromTest()
        {
            // TODO unit test for the property 'ValidFrom'
        }
        /// <summary>
        /// Test the property 'RouteSectionNaptanEntrySequence'
        /// </summary>
        [Test]
        public void RouteSectionNaptanEntrySequenceTest()
        {
            // TODO unit test for the property 'RouteSectionNaptanEntrySequence'
        }

    }

}
