/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesMatchedStop
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesMatchedStopTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesMatchedStop
        //private TflApiPresentationEntitiesMatchedStop instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesMatchedStop
            //instance = new TflApiPresentationEntitiesMatchedStop();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesMatchedStop
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesMatchedStopInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesMatchedStop
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesMatchedStop> (instance, "variable 'instance' is a TflApiPresentationEntitiesMatchedStop");
        }


        /// <summary>
        /// Test the property 'RouteId'
        /// </summary>
        [Test]
        public void RouteIdTest()
        {
            // TODO unit test for the property 'RouteId'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Test]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'StationId'
        /// </summary>
        [Test]
        public void StationIdTest()
        {
            // TODO unit test for the property 'StationId'
        }
        /// <summary>
        /// Test the property 'IcsId'
        /// </summary>
        [Test]
        public void IcsIdTest()
        {
            // TODO unit test for the property 'IcsId'
        }
        /// <summary>
        /// Test the property 'TopMostParentId'
        /// </summary>
        [Test]
        public void TopMostParentIdTest()
        {
            // TODO unit test for the property 'TopMostParentId'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'Towards'
        /// </summary>
        [Test]
        public void TowardsTest()
        {
            // TODO unit test for the property 'Towards'
        }
        /// <summary>
        /// Test the property 'Modes'
        /// </summary>
        [Test]
        public void ModesTest()
        {
            // TODO unit test for the property 'Modes'
        }
        /// <summary>
        /// Test the property 'StopType'
        /// </summary>
        [Test]
        public void StopTypeTest()
        {
            // TODO unit test for the property 'StopType'
        }
        /// <summary>
        /// Test the property 'StopLetter'
        /// </summary>
        [Test]
        public void StopLetterTest()
        {
            // TODO unit test for the property 'StopLetter'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }
        /// <summary>
        /// Test the property 'AccessibilitySummary'
        /// </summary>
        [Test]
        public void AccessibilitySummaryTest()
        {
            // TODO unit test for the property 'AccessibilitySummary'
        }
        /// <summary>
        /// Test the property 'HasDisruption'
        /// </summary>
        [Test]
        public void HasDisruptionTest()
        {
            // TODO unit test for the property 'HasDisruption'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Test]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }

    }

}
