/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesRouteSectionNaptanEntrySequenceTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
        //private TflApiPresentationEntitiesRouteSectionNaptanEntrySequence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
            //instance = new TflApiPresentationEntitiesRouteSectionNaptanEntrySequence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesRouteSectionNaptanEntrySequenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesRouteSectionNaptanEntrySequence
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesRouteSectionNaptanEntrySequence> (instance, "variable 'instance' is a TflApiPresentationEntitiesRouteSectionNaptanEntrySequence");
        }


        /// <summary>
        /// Test the property 'Ordinal'
        /// </summary>
        [Test]
        public void OrdinalTest()
        {
            // TODO unit test for the property 'Ordinal'
        }
        /// <summary>
        /// Test the property 'StopPoint'
        /// </summary>
        [Test]
        public void StopPointTest()
        {
            // TODO unit test for the property 'StopPoint'
        }

    }

}
