/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesStopPointSequence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesStopPointSequenceTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesStopPointSequence
        //private TflApiPresentationEntitiesStopPointSequence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesStopPointSequence
            //instance = new TflApiPresentationEntitiesStopPointSequence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesStopPointSequence
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesStopPointSequenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesStopPointSequence
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesStopPointSequence> (instance, "variable 'instance' is a TflApiPresentationEntitiesStopPointSequence");
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'LineName'
        /// </summary>
        [Test]
        public void LineNameTest()
        {
            // TODO unit test for the property 'LineName'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'BranchId'
        /// </summary>
        [Test]
        public void BranchIdTest()
        {
            // TODO unit test for the property 'BranchId'
        }
        /// <summary>
        /// Test the property 'NextBranchIds'
        /// </summary>
        [Test]
        public void NextBranchIdsTest()
        {
            // TODO unit test for the property 'NextBranchIds'
        }
        /// <summary>
        /// Test the property 'PrevBranchIds'
        /// </summary>
        [Test]
        public void PrevBranchIdsTest()
        {
            // TODO unit test for the property 'PrevBranchIds'
        }
        /// <summary>
        /// Test the property 'StopPoint'
        /// </summary>
        [Test]
        public void StopPointTest()
        {
            // TODO unit test for the property 'StopPoint'
        }
        /// <summary>
        /// Test the property 'ServiceType'
        /// </summary>
        [Test]
        public void ServiceTypeTest()
        {
            // TODO unit test for the property 'ServiceType'
        }

    }

}
