/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesFaresRecommendation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesFaresRecommendationTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesFaresRecommendation
        //private TflApiPresentationEntitiesFaresRecommendation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesFaresRecommendation
            //instance = new TflApiPresentationEntitiesFaresRecommendation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesFaresRecommendation
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesFaresRecommendationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesFaresRecommendation
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesFaresRecommendation> (instance, "variable 'instance' is a TflApiPresentationEntitiesFaresRecommendation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Rule'
        /// </summary>
        [Test]
        public void RuleTest()
        {
            // TODO unit test for the property 'Rule'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'FareType'
        /// </summary>
        [Test]
        public void FareTypeTest()
        {
            // TODO unit test for the property 'FareType'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Test]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'TicketType'
        /// </summary>
        [Test]
        public void TicketTypeTest()
        {
            // TODO unit test for the property 'TicketType'
        }
        /// <summary>
        /// Test the property 'TicketTime'
        /// </summary>
        [Test]
        public void TicketTimeTest()
        {
            // TODO unit test for the property 'TicketTime'
        }
        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [Test]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }
        /// <summary>
        /// Test the property 'DiscountCard'
        /// </summary>
        [Test]
        public void DiscountCardTest()
        {
            // TODO unit test for the property 'DiscountCard'
        }
        /// <summary>
        /// Test the property 'Zones'
        /// </summary>
        [Test]
        public void ZonesTest()
        {
            // TODO unit test for the property 'Zones'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'PriceDescription'
        /// </summary>
        [Test]
        public void PriceDescriptionTest()
        {
            // TODO unit test for the property 'PriceDescription'
        }
        /// <summary>
        /// Test the property 'PriceComparison'
        /// </summary>
        [Test]
        public void PriceComparisonTest()
        {
            // TODO unit test for the property 'PriceComparison'
        }
        /// <summary>
        /// Test the property 'RecommendedTopUp'
        /// </summary>
        [Test]
        public void RecommendedTopUpTest()
        {
            // TODO unit test for the property 'RecommendedTopUp'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'KeyFeatures'
        /// </summary>
        [Test]
        public void KeyFeaturesTest()
        {
            // TODO unit test for the property 'KeyFeatures'
        }
        /// <summary>
        /// Test the property 'GettingYourTicket'
        /// </summary>
        [Test]
        public void GettingYourTicketTest()
        {
            // TODO unit test for the property 'GettingYourTicket'
        }
        /// <summary>
        /// Test the property 'SingleFare'
        /// </summary>
        [Test]
        public void SingleFareTest()
        {
            // TODO unit test for the property 'SingleFare'
        }

    }

}
