/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesRouteSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesRouteSearchResponseTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesRouteSearchResponse
        //private TflApiPresentationEntitiesRouteSearchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesRouteSearchResponse
            //instance = new TflApiPresentationEntitiesRouteSearchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesRouteSearchResponse
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesRouteSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesRouteSearchResponse
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesRouteSearchResponse> (instance, "variable 'instance' is a TflApiPresentationEntitiesRouteSearchResponse");
        }


        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'SearchMatches'
        /// </summary>
        [Test]
        public void SearchMatchesTest()
        {
            // TODO unit test for the property 'SearchMatches'
        }

    }

}
