/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesStreetSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesStreetSegmentTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesStreetSegment
        //private TflApiPresentationEntitiesStreetSegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesStreetSegment
            //instance = new TflApiPresentationEntitiesStreetSegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesStreetSegment
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesStreetSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesStreetSegment
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesStreetSegment> (instance, "variable 'instance' is a TflApiPresentationEntitiesStreetSegment");
        }


        /// <summary>
        /// Test the property 'Toid'
        /// </summary>
        [Test]
        public void ToidTest()
        {
            // TODO unit test for the property 'Toid'
        }
        /// <summary>
        /// Test the property 'LineString'
        /// </summary>
        [Test]
        public void LineStringTest()
        {
            // TODO unit test for the property 'LineString'
        }
        /// <summary>
        /// Test the property 'SourceSystemId'
        /// </summary>
        [Test]
        public void SourceSystemIdTest()
        {
            // TODO unit test for the property 'SourceSystemId'
        }
        /// <summary>
        /// Test the property 'SourceSystemKey'
        /// </summary>
        [Test]
        public void SourceSystemKeyTest()
        {
            // TODO unit test for the property 'SourceSystemKey'
        }

    }

}
