/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesInstructionStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesInstructionStepTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesInstructionStep
        //private TflApiPresentationEntitiesInstructionStep instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesInstructionStep
            //instance = new TflApiPresentationEntitiesInstructionStep();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesInstructionStep
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesInstructionStepInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesInstructionStep
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesInstructionStep> (instance, "variable 'instance' is a TflApiPresentationEntitiesInstructionStep");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TurnDirection'
        /// </summary>
        [Test]
        public void TurnDirectionTest()
        {
            // TODO unit test for the property 'TurnDirection'
        }
        /// <summary>
        /// Test the property 'StreetName'
        /// </summary>
        [Test]
        public void StreetNameTest()
        {
            // TODO unit test for the property 'StreetName'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'CumulativeDistance'
        /// </summary>
        [Test]
        public void CumulativeDistanceTest()
        {
            // TODO unit test for the property 'CumulativeDistance'
        }
        /// <summary>
        /// Test the property 'SkyDirection'
        /// </summary>
        [Test]
        public void SkyDirectionTest()
        {
            // TODO unit test for the property 'SkyDirection'
        }
        /// <summary>
        /// Test the property 'SkyDirectionDescription'
        /// </summary>
        [Test]
        public void SkyDirectionDescriptionTest()
        {
            // TODO unit test for the property 'SkyDirectionDescription'
        }
        /// <summary>
        /// Test the property 'CumulativeTravelTime'
        /// </summary>
        [Test]
        public void CumulativeTravelTimeTest()
        {
            // TODO unit test for the property 'CumulativeTravelTime'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'PathAttribute'
        /// </summary>
        [Test]
        public void PathAttributeTest()
        {
            // TODO unit test for the property 'PathAttribute'
        }
        /// <summary>
        /// Test the property 'DescriptionHeading'
        /// </summary>
        [Test]
        public void DescriptionHeadingTest()
        {
            // TODO unit test for the property 'DescriptionHeading'
        }
        /// <summary>
        /// Test the property 'TrackType'
        /// </summary>
        [Test]
        public void TrackTypeTest()
        {
            // TODO unit test for the property 'TrackType'
        }

    }

}
