/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesRouteSequence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesRouteSequenceTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesRouteSequence
        //private TflApiPresentationEntitiesRouteSequence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesRouteSequence
            //instance = new TflApiPresentationEntitiesRouteSequence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesRouteSequence
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesRouteSequenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesRouteSequence
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesRouteSequence> (instance, "variable 'instance' is a TflApiPresentationEntitiesRouteSequence");
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'LineName'
        /// </summary>
        [Test]
        public void LineNameTest()
        {
            // TODO unit test for the property 'LineName'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'IsOutboundOnly'
        /// </summary>
        [Test]
        public void IsOutboundOnlyTest()
        {
            // TODO unit test for the property 'IsOutboundOnly'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'LineStrings'
        /// </summary>
        [Test]
        public void LineStringsTest()
        {
            // TODO unit test for the property 'LineStrings'
        }
        /// <summary>
        /// Test the property 'Stations'
        /// </summary>
        [Test]
        public void StationsTest()
        {
            // TODO unit test for the property 'Stations'
        }
        /// <summary>
        /// Test the property 'StopPointSequences'
        /// </summary>
        [Test]
        public void StopPointSequencesTest()
        {
            // TODO unit test for the property 'StopPointSequences'
        }
        /// <summary>
        /// Test the property 'OrderedLineRoutes'
        /// </summary>
        [Test]
        public void OrderedLineRoutesTest()
        {
            // TODO unit test for the property 'OrderedLineRoutes'
        }

    }

}
