/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesAccidentStatsAccidentDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesAccidentStatsAccidentDetailTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesAccidentStatsAccidentDetail
        //private TflApiPresentationEntitiesAccidentStatsAccidentDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesAccidentStatsAccidentDetail
            //instance = new TflApiPresentationEntitiesAccidentStatsAccidentDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesAccidentStatsAccidentDetail
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesAccidentStatsAccidentDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesAccidentStatsAccidentDetail
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesAccidentStatsAccidentDetail> (instance, "variable 'instance' is a TflApiPresentationEntitiesAccidentStatsAccidentDetail");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Test]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'Borough'
        /// </summary>
        [Test]
        public void BoroughTest()
        {
            // TODO unit test for the property 'Borough'
        }
        /// <summary>
        /// Test the property 'Casualties'
        /// </summary>
        [Test]
        public void CasualtiesTest()
        {
            // TODO unit test for the property 'Casualties'
        }
        /// <summary>
        /// Test the property 'Vehicles'
        /// </summary>
        [Test]
        public void VehiclesTest()
        {
            // TODO unit test for the property 'Vehicles'
        }

    }

}
