@startuml
class TflModelWrapper {
    - <<readonly>> _cachePath : string
    - <<const>> MaxCacheAge : int = 30
    - <<const>> PercentOfTotal : int = 90
    - <<const>> InitialPercent : double = 3.0
    + TflModelWrapper(logger:ILogger, cachePath:string)
    - AddLineSeqLinks(segments:List<TflApiPresentationEntitiesStopPointSequence>, network:Network, currentLineId:string, direction:Dir) : void
    - EnsureCacheUpdated() : void
    + PopulateNetworkStructure(network:Network) : void
    + SetProgressCallback(callback:Action<double>) : void
    - PopulateNetworkStructureFromCache(network:Network) : void
    - UpdateStructureCache() : void
    - UpdateTimingsLib() : void
    - PopulateNetworkTimesTimingsLib(network:Network) : void
}
class "Action`1"<T> {
}
INetworkDataSource <|-- TflModelWrapper
TflModelWrapper --> "_lineApi" LineApi
TflModelWrapper --> "_logger" ILogger
TflModelWrapper o-> "_progressCallback<double>" "Action`1"
@enduml
