@startuml
class TflModelWrapper {
    - cachePath : string
    - <<const>> maxCacheAge : int = 30
    + TflModelWrapper(logger:ILogger, cachePath:string)
    <<internal>> GetSequenceById(segments:List<TflApiPresentationEntitiesStopPointSequence>, id:int) : TflApiPresentationEntitiesStopPointSequence
    <<internal>> GetFirstStop(segment:TflApiPresentationEntitiesStopPointSequence) : TflApiPresentationEntitiesMatchedStop
    <<internal>> GetLastStop(segment:TflApiPresentationEntitiesStopPointSequence) : TflApiPresentationEntitiesMatchedStop
    + AddLinksForLineSequence(segments:List<TflApiPresentationEntitiesStopPointSequence>, network:Network, currentLine:Line, direction:Dir) : void
    + PopulateNetworkStructure(network:Network) : void
    - PopulateNetworkStructureFromCache(network:Network) : void
    - UpdateStructureCache() : void
    - UpdateEliyahuLib() : void
    - PopulateNetworkTimesEliyahuLib(network:Network) : void
    - PopulateNetworkTimes(network:Network) : void
    - UpdateTimetableCache() : void
}
INetworkDataFetcher <|-- TflModelWrapper
TflModelWrapper --> "stationFetcher" StopPointApi
TflModelWrapper --> "lineApi" LineApi
TflModelWrapper --> "logger" ILogger
@enduml
