@startuml
class StrictAnnealingSolver {
    + StrictAnnealingSolver(logger:ILogger)
    + StrictAnnealingSolver(logger:ILogger, progressCallback:Action<double>)
    + <<override>> Solve(net:Network) : Route
}
AnnealingSolver <|-- StrictAnnealingSolver
ISolver <|-- StrictAnnealingSolver
@enduml
