@startuml
class TflApiPresentationEntitiesInstructionStepTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesInstructionStepInstanceTest() : void
    + DescriptionTest() : void
    + TurnDirectionTest() : void
    + StreetNameTest() : void
    + DistanceTest() : void
    + CumulativeDistanceTest() : void
    + SkyDirectionTest() : void
    + SkyDirectionDescriptionTest() : void
    + CumulativeTravelTimeTest() : void
    + LatitudeTest() : void
    + LongitudeTest() : void
    + PathAttributeTest() : void
    + DescriptionHeadingTest() : void
    + TrackTypeTest() : void
}
@enduml
