@startuml
class TflApiPresentationEntitiesCrowdingTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesCrowdingInstanceTest() : void
    + PassengerFlowsTest() : void
    + TrainLoadingsTest() : void
}
@enduml
