@startuml
class TflApiPresentationEntitiesDisruptedPointTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesDisruptedPointInstanceTest() : void
    + AtcoCodeTest() : void
    + FromDateTest() : void
    + ToDateTest() : void
    + DescriptionTest() : void
    + CommonNameTest() : void
    + TypeTest() : void
    + ModeTest() : void
    + StationAtcoCodeTest() : void
    + AppearanceTest() : void
    + AdditionalInformationTest() : void
}
@enduml
