@startuml
class TflApiPresentationEntitiesTimetableRouteTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesTimetableRouteInstanceTest() : void
    + StationIntervalsTest() : void
    + SchedulesTest() : void
}
@enduml
