@startuml
class TflApiPresentationEntitiesJourneyPlannerFareCaveatTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerFareCaveatInstanceTest() : void
    + TextTest() : void
    + TypeTest() : void
}
@enduml
