@startuml
class TflApiPresentationEntitiesFaresFareTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFareInstanceTest() : void
    + IdTest() : void
    + PassengerTypeTest() : void
    + ValidFromTest() : void
    + ValidUntilTest() : void
    + TicketTimeTest() : void
    + TicketTypeTest() : void
    + CostTest() : void
    + CapTest() : void
    + DescriptionTest() : void
    + ZoneTest() : void
    + ModeTest() : void
}
@enduml
