@startuml
class TflApiPresentationEntitiesFaresTicketTimeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresTicketTimeInstanceTest() : void
    + TypeTest() : void
    + DescriptionTest() : void
}
@enduml
