@startuml
class TflApiPresentationEntitiesPointTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPointInstanceTest() : void
    + LatTest() : void
    + LonTest() : void
}
@enduml
