@startuml
class TflApiPresentationEntitiesJourneyPlannerJourneyTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerJourneyInstanceTest() : void
    + StartDateTimeTest() : void
    + DurationTest() : void
    + ArrivalDateTimeTest() : void
    + DescriptionTest() : void
    + AlternativeRouteTest() : void
    + LegsTest() : void
    + FareTest() : void
}
@enduml
