@startuml
class TflApiPresentationEntitiesLineModeGroupTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesLineModeGroupInstanceTest() : void
    + ModeNameTest() : void
    + LineIdentifierTest() : void
}
@enduml
