@startuml
class TflApiPresentationEntitiesStopPointRouteSectionTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStopPointRouteSectionInstanceTest() : void
    + NaptanIdTest() : void
    + LineIdTest() : void
    + ModeTest() : void
    + ValidFromTest() : void
    + ValidToTest() : void
    + DirectionTest() : void
    + RouteSectionNameTest() : void
    + LineStringTest() : void
    + IsActiveTest() : void
    + ServiceTypeTest() : void
    + VehicleDestinationTextTest() : void
    + DestinationNameTest() : void
}
@enduml
