@startuml
class TflApiPresentationEntitiesFaresFaresSectionTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFaresSectionInstanceTest() : void
    + HeaderTest() : void
    + IndexTest() : void
    + JourneyTest() : void
    + RowsTest() : void
    + MessagesTest() : void
}
@enduml
