@startuml
class TflApiPresentationEntitiesJourneyPlannerObstacleTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerObstacleInstanceTest() : void
    + TypeTest() : void
    + InclineTest() : void
    + StopIdTest() : void
    + PositionTest() : void
}
@enduml
