@startuml
class TflApiPresentationEntitiesStopPointTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStopPointInstanceTest() : void
    + NaptanIdTest() : void
    + PlatformNameTest() : void
    + IndicatorTest() : void
    + StopLetterTest() : void
    + ModesTest() : void
    + IcsCodeTest() : void
    + SmsCodeTest() : void
    + StopTypeTest() : void
    + StationNaptanTest() : void
    + AccessibilitySummaryTest() : void
    + HubNaptanCodeTest() : void
    + LinesTest() : void
    + LineGroupTest() : void
    + LineModeGroupsTest() : void
    + FullNameTest() : void
    + NaptanModeTest() : void
    + StatusTest() : void
    + IndividualStopIdTest() : void
    + IdTest() : void
    + UrlTest() : void
    + CommonNameTest() : void
    + DistanceTest() : void
    + PlaceTypeTest() : void
    + AdditionalPropertiesTest() : void
    + ChildrenTest() : void
    + ChildrenUrlsTest() : void
    + LatTest() : void
    + LonTest() : void
}
@enduml
