@startuml
class TflApiPresentationEntitiesStatusSeverityTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStatusSeverityInstanceTest() : void
    + ModeNameTest() : void
    + SeverityLevelTest() : void
    + DescriptionTest() : void
}
@enduml
