@startuml
class TflApiPresentationEntitiesServiceFrequencyTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesServiceFrequencyInstanceTest() : void
    + LowestFrequencyTest() : void
    + HighestFrequencyTest() : void
}
@enduml
