@startuml
class TflApiPresentationEntitiesModeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesModeInstanceTest() : void
    + IsTflServiceTest() : void
    + IsFarePayingTest() : void
    + IsScheduledServiceTest() : void
    + ModeNameTest() : void
    + MotTypeTest() : void
    + NetworkTest() : void
}
@enduml
