@startuml
class TflApiPresentationEntitiesBikePointOccupancyTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesBikePointOccupancyInstanceTest() : void
    + IdTest() : void
    + NameTest() : void
    + BikesCountTest() : void
    + EmptyDocksTest() : void
    + TotalDocksTest() : void
    + StandardBikesCountTest() : void
    + EBikesCountTest() : void
}
@enduml
