@startuml
class TflApiPresentationEntitiesSearchMatchTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesSearchMatchInstanceTest() : void
    + IdTest() : void
    + UrlTest() : void
    + NameTest() : void
    + LatTest() : void
    + LonTest() : void
}
@enduml
