@startuml
class TflApiPresentationEntitiesRouteSectionNaptanEntrySequenceTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesRouteSectionNaptanEntrySequenceInstanceTest() : void
    + OrdinalTest() : void
    + StopPointTest() : void
}
@enduml
