@startuml
class TflApiPresentationEntitiesJourneyPlannerFareTapDetailsTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerFareTapDetailsInstanceTest() : void
    + ModeTypeTest() : void
    + ValidationTypeTest() : void
    + HostDeviceTypeTest() : void
    + BusRouteIdTest() : void
    + NationalLocationCodeTest() : void
    + TapTimestampTest() : void
}
@enduml
