@startuml
class TflApiPresentationEntitiesPassengerFlowTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPassengerFlowInstanceTest() : void
    + TimeSliceTest() : void
    + ValueTest() : void
}
@enduml
