@startuml
class TflApiPresentationEntitiesFaresTicketTypeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresTicketTypeInstanceTest() : void
    + TypeTest() : void
    + DescriptionTest() : void
}
@enduml
