@startuml
class TflApiPresentationEntitiesFaresFareStationTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFareStationInstanceTest() : void
    + AtcoCodeTest() : void
    + CommonNameTest() : void
    + FareCategoryTest() : void
}
@enduml
