@startuml
class TflApiPresentationEntitiesFaresRecommendationResponseTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresRecommendationResponseInstanceTest() : void
    + RecommendationsTest() : void
}
@enduml
