@startuml
class TflApiPresentationEntitiesPathAttributeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPathAttributeInstanceTest() : void
    + NameTest() : void
    + ValueTest() : void
}
@enduml
