@startuml
class TflApiPresentationEntitiesChargeConnectorOccupancyTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesChargeConnectorOccupancyInstanceTest() : void
    + IdTest() : void
    + SourceSystemPlaceIdTest() : void
    + StatusTest() : void
}
@enduml
