@startuml
class TflApiPresentationEntitiesJourneyPlannerFareTapTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerFareTapInstanceTest() : void
    + AtcoCodeTest() : void
    + TapDetailsTest() : void
}
@enduml
