@startuml
class TflApiPresentationEntitiesPlacePolygonTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPlacePolygonInstanceTest() : void
    + GeoPointsTest() : void
    + CommonNameTest() : void
}
@enduml
