@startuml
class TflApiPresentationEntitiesFaresFareDetailsTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFareDetailsInstanceTest() : void
    + BoundsIdTest() : void
    + StartDateTest() : void
    + EndDateTest() : void
    + ModeTest() : void
    + PassengerTypeTest() : void
    + ContactlessPAYGOnlyFareTest() : void
    + FromTest() : void
    + ToTest() : void
    + FromStationTest() : void
    + ToStationTest() : void
    + ViaTest() : void
    + RouteCodeTest() : void
    + DisplayNameTest() : void
    + DisplayOrderTest() : void
    + RouteDescriptionTest() : void
    + ValidatorInformationTest() : void
    + OperatorTest() : void
    + SpecialFareTest() : void
    + ThroughFareTest() : void
    + IsTourTest() : void
    + TicketsAvailableTest() : void
    + MessagesTest() : void
}
@enduml
