@startuml
class TflApiPresentationEntitiesFaresFareBoundsTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFareBoundsInstanceTest() : void
    + IdTest() : void
    + FromTest() : void
    + ToTest() : void
    + ViaTest() : void
    + RouteCodeTest() : void
    + DescriptionTest() : void
    + DisplayNameTest() : void
    + OperatorTest() : void
    + DisplayOrderTest() : void
    + IsPopularFareTest() : void
    + IsPopularTravelCardTest() : void
    + IsTourTest() : void
    + MessagesTest() : void
}
@enduml
