@startuml
class TflApiPresentationEntitiesLineTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesLineInstanceTest() : void
    + IdTest() : void
    + NameTest() : void
    + ModeNameTest() : void
    + DisruptionsTest() : void
    + CreatedTest() : void
    + ModifiedTest() : void
    + LineStatusesTest() : void
    + RouteSectionsTest() : void
    + ServiceTypesTest() : void
    + CrowdingTest() : void
}
@enduml
