@startuml
class TflApiCommonApiVersionInfoTests {
    + Init() : void
    + Cleanup() : void
    + TflApiCommonApiVersionInfoInstanceTest() : void
    + LabelTest() : void
    + TimestampTest() : void
    + VersionTest() : void
    + AssembliesTest() : void
}
@enduml
