@startuml
class TflApiPresentationEntitiesFaresFaresPeriodTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFaresPeriodInstanceTest() : void
    + IdTest() : void
    + StartDateTest() : void
    + ViewableDateTest() : void
    + EndDateTest() : void
    + IsFutureTest() : void
}
@enduml
