@startuml
class TflApiPresentationEntitiesMatchedRouteSectionsTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesMatchedRouteSectionsInstanceTest() : void
    + IdTest() : void
}
@enduml
