@startuml
class TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationDataTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationDataInstanceTest() : void
    + OriginNumberOfBikesTest() : void
    + DestinationNumberOfBikesTest() : void
    + OriginNumberOfEmptySlotsTest() : void
    + DestinationNumberOfEmptySlotsTest() : void
    + OriginIdTest() : void
    + DestinationIdTest() : void
}
@enduml
