@startuml
class TflApiPresentationEntitiesRoadDisruptionScheduleTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesRoadDisruptionScheduleInstanceTest() : void
    + StartTimeTest() : void
    + EndTimeTest() : void
}
@enduml
