@startuml
class TflApiCommonJourneyPlannerJpElevationTests {
    + Init() : void
    + Cleanup() : void
    + TflApiCommonJourneyPlannerJpElevationInstanceTest() : void
    + DistanceTest() : void
    + StartLatTest() : void
    + StartLonTest() : void
    + EndLatTest() : void
    + EndLonTest() : void
    + HeightFromPreviousPointTest() : void
    + GradientTest() : void
}
@enduml
