@startuml
class TflApiPresentationEntitiesPlaceTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPlaceInstanceTest() : void
    + IdTest() : void
    + UrlTest() : void
    + CommonNameTest() : void
    + DistanceTest() : void
    + PlaceTypeTest() : void
    + AdditionalPropertiesTest() : void
    + ChildrenTest() : void
    + ChildrenUrlsTest() : void
    + LatTest() : void
    + LonTest() : void
}
@enduml
