@startuml
class TflApiPresentationEntitiesArrivalDepartureTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesArrivalDepartureInstanceTest() : void
    + PlatformNameTest() : void
    + DestinationNaptanIdTest() : void
    + DestinationNameTest() : void
    + NaptanIdTest() : void
    + StationNameTest() : void
    + EstimatedTimeOfArrivalTest() : void
    + ScheduledTimeOfArrivalTest() : void
    + EstimatedTimeOfDepartureTest() : void
    + ScheduledTimeOfDepartureTest() : void
    + MinutesAndSecondsToArrivalTest() : void
    + MinutesAndSecondsToDepartureTest() : void
    + CauseTest() : void
    + DepartureStatusTest() : void
    + TimingTest() : void
}
@enduml
