@startuml
class TflApiPresentationEntitiesTimetablesDisambiguationOptionTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesTimetablesDisambiguationOptionInstanceTest() : void
    + DescriptionTest() : void
    + UriTest() : void
}
@enduml
