@startuml
class TflApiPresentationEntitiesStopPointSequenceTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStopPointSequenceInstanceTest() : void
    + LineIdTest() : void
    + LineNameTest() : void
    + DirectionTest() : void
    + BranchIdTest() : void
    + NextBranchIdsTest() : void
    + PrevBranchIdsTest() : void
    + StopPointTest() : void
    + ServiceTypeTest() : void
}
@enduml
