@startuml
class TflApiPresentationEntitiesIntervalTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesIntervalInstanceTest() : void
    + StopIdTest() : void
    + TimeToArrivalTest() : void
}
@enduml
