@startuml
class TflApiPresentationEntitiesJourneyPlannerTimeAdjustmentsTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerTimeAdjustmentsInstanceTest() : void
    + EarliestTest() : void
    + EarlierTest() : void
    + LaterTest() : void
    + LatestTest() : void
}
@enduml
