@startuml
class TflApiPresentationEntitiesAccidentStatsAccidentDetailTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesAccidentStatsAccidentDetailInstanceTest() : void
    + IdTest() : void
    + LatTest() : void
    + LonTest() : void
    + LocationTest() : void
    + DateTest() : void
    + SeverityTest() : void
    + BoroughTest() : void
    + CasualtiesTest() : void
    + VehiclesTest() : void
}
@enduml
