@startuml
class TflApiPresentationEntitiesIdentifierTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesIdentifierInstanceTest() : void
    + IdTest() : void
    + NameTest() : void
    + UriTest() : void
    + FullNameTest() : void
    + TypeTest() : void
    + CrowdingTest() : void
    + RouteTypeTest() : void
    + StatusTest() : void
    + MotTypeTest() : void
    + NetworkTest() : void
}
@enduml
