@startuml
class TflApiPresentationEntitiesJourneyPlannerLegTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerLegInstanceTest() : void
    + DurationTest() : void
    + SpeedTest() : void
    + InstructionTest() : void
    + ObstaclesTest() : void
    + DepartureTimeTest() : void
    + ArrivalTimeTest() : void
    + DeparturePointTest() : void
    + ArrivalPointTest() : void
    + PathTest() : void
    + RouteOptionsTest() : void
    + ModeTest() : void
    + DisruptionsTest() : void
    + PlannedWorksTest() : void
    + DistanceTest() : void
    + IsDisruptedTest() : void
    + HasFixedLocationsTest() : void
    + ScheduledDepartureTimeTest() : void
    + ScheduledArrivalTimeTest() : void
    + InterChangeDurationTest() : void
    + InterChangePositionTest() : void
}
@enduml
