@startuml
class TflApiPresentationEntitiesFaresFaresModeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesFaresFaresModeInstanceTest() : void
    + IdTest() : void
    + NameTest() : void
    + DescriptionTest() : void
}
@enduml
