@startuml
class TflApiPresentationEntitiesPlaceCategoryTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesPlaceCategoryInstanceTest() : void
    + CategoryTest() : void
    + AvailableKeysTest() : void
}
@enduml
