@startuml
class TflApiPresentationEntitiesStopPointCategoryTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStopPointCategoryInstanceTest() : void
    + CategoryTest() : void
    + AvailableKeysTest() : void
}
@enduml
