@startuml
class TflApiPresentationEntitiesJourneyPlannerJourneyVectorTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerJourneyVectorInstanceTest() : void
    + FromTest() : void
    + ToTest() : void
    + ViaTest() : void
    + UriTest() : void
}
@enduml
