@startuml
class TflApiPresentationEntitiesValidityPeriodTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesValidityPeriodInstanceTest() : void
    + FromDateTest() : void
    + ToDateTest() : void
    + IsNowTest() : void
}
@enduml
