@startuml
class TflApiPresentationEntitiesAdditionalPropertiesTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesAdditionalPropertiesInstanceTest() : void
    + CategoryTest() : void
    + KeyTest() : void
    + SourceSystemKeyTest() : void
    + ValueTest() : void
    + ModifiedTest() : void
}
@enduml
