@startuml
class TflApiPresentationEntitiesTimetablesDisambiguationTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesTimetablesDisambiguationInstanceTest() : void
    + DisambiguationOptionsTest() : void
}
@enduml
