@startuml
class TflApiPresentationEntitiesLineStatusTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesLineStatusInstanceTest() : void
    + IdTest() : void
    + LineIdTest() : void
    + StatusSeverityTest() : void
    + StatusSeverityDescriptionTest() : void
    + ReasonTest() : void
    + CreatedTest() : void
    + ModifiedTest() : void
    + ValidityPeriodsTest() : void
    + DisruptionTest() : void
}
@enduml
