@startuml
class TflApiPresentationEntitiesStopPointsResponseTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesStopPointsResponseInstanceTest() : void
    + CentrePointTest() : void
    + StopPointsTest() : void
    + PageSizeTest() : void
    + TotalTest() : void
    + PageTest() : void
}
@enduml
