@startuml
class TflApiPresentationEntitiesDisruptionTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesDisruptionInstanceTest() : void
    + CategoryTest() : void
    + TypeTest() : void
    + CategoryDescriptionTest() : void
    + DescriptionTest() : void
    + SummaryTest() : void
    + AdditionalInfoTest() : void
    + CreatedTest() : void
    + LastUpdateTest() : void
    + AffectedRoutesTest() : void
    + AffectedStopsTest() : void
    + ClosureTextTest() : void
}
@enduml
