@startuml
class TflApiPresentationEntitiesActiveServiceTypeTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesActiveServiceTypeInstanceTest() : void
    + ModeTest() : void
    + ServiceTypeTest() : void
}
@enduml
