@startuml
class TflApiPresentationEntitiesRouteSequenceTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesRouteSequenceInstanceTest() : void
    + LineIdTest() : void
    + LineNameTest() : void
    + DirectionTest() : void
    + IsOutboundOnlyTest() : void
    + ModeTest() : void
    + LineStringsTest() : void
    + StationsTest() : void
    + StopPointSequencesTest() : void
    + OrderedLineRoutesTest() : void
}
@enduml
