@startuml
class TflApiPresentationEntitiesAccidentStatsVehicleTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesAccidentStatsVehicleInstanceTest() : void
    + TypeTest() : void
}
@enduml
