@startuml
class TflApiPresentationEntitiesJourneyPlannerPlannedWorkTests {
    + Init() : void
    + Cleanup() : void
    + TflApiPresentationEntitiesJourneyPlannerPlannedWorkInstanceTest() : void
    + IdTest() : void
    + DescriptionTest() : void
    + CreatedDateTimeTest() : void
    + LastUpdateDateTimeTest() : void
}
@enduml
