@startuml
interface IAirQualityApi {
}
class AirQualityApi <<partial>> {
    + AirQualityApi(basePath:String)
    + AirQualityApi(configuration:IO.Swagger.Client.Configuration)
    + GetBasePath() : String
    + SetBasePath(basePath:String) : void
    + DefaultHeader() : IDictionary<String, String>
    + AddDefaultHeader(key:string, value:string) : void
    + AirQualityGet() : SystemObject
    + AirQualityGetWithHttpInfo() : ApiResponse< SystemObject >
    + <<async>> AirQualityGetAsync() : System.Threading.Tasks.Task<SystemObject>
    + <<async>> AirQualityGetAsyncWithHttpInfo() : System.Threading.Tasks.Task<ApiResponse<SystemObject>>
}
IApiAccessor <|-- IAirQualityApi
IAirQualityApi <|-- AirQualityApi
@enduml
