@startuml
interface ISearchApi {
}
class SearchApi <<partial>> {
    + SearchApi(basePath:String)
    + SearchApi(configuration:IO.Swagger.Client.Configuration)
    + GetBasePath() : String
    + SetBasePath(basePath:String) : void
    + DefaultHeader() : IDictionary<String, String>
    + AddDefaultHeader(key:string, value:string) : void
    + SearchBusSchedules(query:string) : TflApiPresentationEntitiesSearchResponse
    + SearchBusSchedulesWithHttpInfo(query:string) : ApiResponse< TflApiPresentationEntitiesSearchResponse >
    + <<async>> SearchBusSchedulesAsync(query:string) : System.Threading.Tasks.Task<TflApiPresentationEntitiesSearchResponse>
    + <<async>> SearchBusSchedulesAsyncWithHttpInfo(query:string) : System.Threading.Tasks.Task<ApiResponse<TflApiPresentationEntitiesSearchResponse>>
    + SearchGet(query:string) : TflApiPresentationEntitiesSearchResponse
    + SearchGetWithHttpInfo(query:string) : ApiResponse< TflApiPresentationEntitiesSearchResponse >
    + <<async>> SearchGetAsync(query:string) : System.Threading.Tasks.Task<TflApiPresentationEntitiesSearchResponse>
    + <<async>> SearchGetAsyncWithHttpInfo(query:string) : System.Threading.Tasks.Task<ApiResponse<TflApiPresentationEntitiesSearchResponse>>
    + SearchMetaCategories() : List<string>
    + SearchMetaCategoriesWithHttpInfo() : ApiResponse< List<string> >
    + <<async>> SearchMetaCategoriesAsync() : System.Threading.Tasks.Task<List<string>>
    + <<async>> SearchMetaCategoriesAsyncWithHttpInfo() : System.Threading.Tasks.Task<ApiResponse<List<string>>>
    + SearchMetaSearchProviders() : List<string>
    + SearchMetaSearchProvidersWithHttpInfo() : ApiResponse< List<string> >
    + <<async>> SearchMetaSearchProvidersAsync() : System.Threading.Tasks.Task<List<string>>
    + <<async>> SearchMetaSearchProvidersAsyncWithHttpInfo() : System.Threading.Tasks.Task<ApiResponse<List<string>>>
    + SearchMetaSorts() : List<string>
    + SearchMetaSortsWithHttpInfo() : ApiResponse< List<string> >
    + <<async>> SearchMetaSortsAsync() : System.Threading.Tasks.Task<List<string>>
    + <<async>> SearchMetaSortsAsyncWithHttpInfo() : System.Threading.Tasks.Task<ApiResponse<List<string>>>
}
IApiAccessor <|-- ISearchApi
ISearchApi <|-- SearchApi
@enduml
