@startuml
class MainWindowViewModel {
    + Greeting : string <<get>>
}
class SimpleViewModel {
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
    - RaisePropertyChanged(propertyName:string?) : void
    - _Name : string?
    + Name : string? <<get>> <<set>>
    + Greeting : string <<get>>
}
ViewModelBase <|-- MainWindowViewModel
MainWindowViewModel o-> "SimpleViewModel" SimpleViewModel
MainWindowViewModel o-> "ReactiveViewModel" ReactiveViewModel
MainWindowViewModel o-> "SVGMapViewModel" SVGMapViewModel
MainWindowViewModel o-> "SolverControlViewModel" SolverControlViewModel
INotifyPropertyChanged <|-- SimpleViewModel
@enduml
