@startuml
class SvgMapViewModel {
    - _stationName : string?
    - _showSvg : bool
    + TestCommand : ICommand <<get>>
    + ConversationLog : ObservableCollection<string> <<get>>
    - _svgMap : SKSvg
    - SvgMap : SKSvg <<get>> <<set>>
    - _svg : Avalonia.Svg.Skia.Svg
    - AddToConvo(content:string) : void
    + SvgMapViewModel()
    + StationName : string? <<get>> <<set>>
    + ShowSvg : bool <<get>> <<set>>
    + UpdateSvg() : void
    - OpenThePodBayDoors() : void
    + CanvasControl_OnDraw(sender:object?, e:SKCanvasEventArgs) : void
    - HideGroup(canvas:SKCanvas, groupId:string) : void
    - HideSvg() : void
}
ReactiveObject <|-- SvgMapViewModel
@enduml
