@startuml
class SvgMapViewModel {
    - _stationName : string?
    - _showSvg : bool
    - AddToConvo(content:string) : void
    + SvgMapViewModel()
    + StationName : string? <<get>> <<set>>
    + ShowSvg : bool <<get>> <<set>>
    + UpdateSvg() : void
    - OpenThePodBayDoors() : void
    + CanvasControl_OnDraw(sender:object?, e:SKCanvasEventArgs) : void
    - HideGroup(canvas:SKCanvas, groupId:string) : void
    - HideSvg() : void
}
class "ObservableCollection`1"<T> {
}
ReactiveObject <|-- SvgMapViewModel
SvgMapViewModel --> "TestCommand" ICommand
SvgMapViewModel o-> "ConversationLog<string>" "ObservableCollection`1"
SvgMapViewModel --> "_svgMap" SKSvg
SvgMapViewModel --> "SvgMap" SKSvg
@enduml
