@startuml
class ViewModelBase {
}
class ReactiveViewModel {
    + ReactiveViewModel()
    - _name : string?
    + Name : string? <<get>> <<set>>
    + Greeting : string <<get>>
}
ReactiveObject <|-- ViewModelBase
ReactiveObject <|-- ReactiveViewModel
@enduml
