@startuml
class SizeTests {
    - _queue : PriorityQueue<int>
    + SetUp() : void
    + EmptyQueue_HasSizeZero() : void
    + InsertingOneItem_IncreasesSize() : void
    + RemovingAllItems_DecreasesSizeToZero() : void
}
@enduml
