/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesJourneyPlannerJourneyVector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesJourneyPlannerJourneyVectorTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesJourneyPlannerJourneyVector
        //private TflApiPresentationEntitiesJourneyPlannerJourneyVector instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesJourneyPlannerJourneyVector
            //instance = new TflApiPresentationEntitiesJourneyPlannerJourneyVector();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesJourneyPlannerJourneyVector
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesJourneyPlannerJourneyVectorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesJourneyPlannerJourneyVector
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesJourneyPlannerJourneyVector> (instance, "variable 'instance' is a TflApiPresentationEntitiesJourneyPlannerJourneyVector");
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Via'
        /// </summary>
        [Test]
        public void ViaTest()
        {
            // TODO unit test for the property 'Via'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
