/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesJourneyPlannerItineraryResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesJourneyPlannerItineraryResultTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesJourneyPlannerItineraryResult
        //private TflApiPresentationEntitiesJourneyPlannerItineraryResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesJourneyPlannerItineraryResult
            //instance = new TflApiPresentationEntitiesJourneyPlannerItineraryResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesJourneyPlannerItineraryResult
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesJourneyPlannerItineraryResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesJourneyPlannerItineraryResult
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesJourneyPlannerItineraryResult> (instance, "variable 'instance' is a TflApiPresentationEntitiesJourneyPlannerItineraryResult");
        }


        /// <summary>
        /// Test the property 'Journeys'
        /// </summary>
        [Test]
        public void JourneysTest()
        {
            // TODO unit test for the property 'Journeys'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Test]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
        /// <summary>
        /// Test the property 'CycleHireDockingStationData'
        /// </summary>
        [Test]
        public void CycleHireDockingStationDataTest()
        {
            // TODO unit test for the property 'CycleHireDockingStationData'
        }
        /// <summary>
        /// Test the property 'StopMessages'
        /// </summary>
        [Test]
        public void StopMessagesTest()
        {
            // TODO unit test for the property 'StopMessages'
        }
        /// <summary>
        /// Test the property 'RecommendedMaxAgeMinutes'
        /// </summary>
        [Test]
        public void RecommendedMaxAgeMinutesTest()
        {
            // TODO unit test for the property 'RecommendedMaxAgeMinutes'
        }
        /// <summary>
        /// Test the property 'SearchCriteria'
        /// </summary>
        [Test]
        public void SearchCriteriaTest()
        {
            // TODO unit test for the property 'SearchCriteria'
        }
        /// <summary>
        /// Test the property 'JourneyVector'
        /// </summary>
        [Test]
        public void JourneyVectorTest()
        {
            // TODO unit test for the property 'JourneyVector'
        }

    }

}
