/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesArrivalDepartureWithLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesArrivalDepartureWithLineTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesArrivalDepartureWithLine
        //private TflApiPresentationEntitiesArrivalDepartureWithLine instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesArrivalDepartureWithLine
            //instance = new TflApiPresentationEntitiesArrivalDepartureWithLine();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesArrivalDepartureWithLine
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesArrivalDepartureWithLineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesArrivalDepartureWithLine
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesArrivalDepartureWithLine> (instance, "variable 'instance' is a TflApiPresentationEntitiesArrivalDepartureWithLine");
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'LineName'
        /// </summary>
        [Test]
        public void LineNameTest()
        {
            // TODO unit test for the property 'LineName'
        }
        /// <summary>
        /// Test the property 'PlatformName'
        /// </summary>
        [Test]
        public void PlatformNameTest()
        {
            // TODO unit test for the property 'PlatformName'
        }
        /// <summary>
        /// Test the property 'DestinationNaptanId'
        /// </summary>
        [Test]
        public void DestinationNaptanIdTest()
        {
            // TODO unit test for the property 'DestinationNaptanId'
        }
        /// <summary>
        /// Test the property 'DestinationName'
        /// </summary>
        [Test]
        public void DestinationNameTest()
        {
            // TODO unit test for the property 'DestinationName'
        }
        /// <summary>
        /// Test the property 'NaptanId'
        /// </summary>
        [Test]
        public void NaptanIdTest()
        {
            // TODO unit test for the property 'NaptanId'
        }
        /// <summary>
        /// Test the property 'StationName'
        /// </summary>
        [Test]
        public void StationNameTest()
        {
            // TODO unit test for the property 'StationName'
        }
        /// <summary>
        /// Test the property 'EstimatedTimeOfArrival'
        /// </summary>
        [Test]
        public void EstimatedTimeOfArrivalTest()
        {
            // TODO unit test for the property 'EstimatedTimeOfArrival'
        }
        /// <summary>
        /// Test the property 'ScheduledTimeOfArrival'
        /// </summary>
        [Test]
        public void ScheduledTimeOfArrivalTest()
        {
            // TODO unit test for the property 'ScheduledTimeOfArrival'
        }
        /// <summary>
        /// Test the property 'EstimatedTimeOfDeparture'
        /// </summary>
        [Test]
        public void EstimatedTimeOfDepartureTest()
        {
            // TODO unit test for the property 'EstimatedTimeOfDeparture'
        }
        /// <summary>
        /// Test the property 'ScheduledTimeOfDeparture'
        /// </summary>
        [Test]
        public void ScheduledTimeOfDepartureTest()
        {
            // TODO unit test for the property 'ScheduledTimeOfDeparture'
        }
        /// <summary>
        /// Test the property 'MinutesAndSecondsToArrival'
        /// </summary>
        [Test]
        public void MinutesAndSecondsToArrivalTest()
        {
            // TODO unit test for the property 'MinutesAndSecondsToArrival'
        }
        /// <summary>
        /// Test the property 'MinutesAndSecondsToDeparture'
        /// </summary>
        [Test]
        public void MinutesAndSecondsToDepartureTest()
        {
            // TODO unit test for the property 'MinutesAndSecondsToDeparture'
        }
        /// <summary>
        /// Test the property 'Cause'
        /// </summary>
        [Test]
        public void CauseTest()
        {
            // TODO unit test for the property 'Cause'
        }
        /// <summary>
        /// Test the property 'DepartureStatus'
        /// </summary>
        [Test]
        public void DepartureStatusTest()
        {
            // TODO unit test for the property 'DepartureStatus'
        }
        /// <summary>
        /// Test the property 'Timing'
        /// </summary>
        [Test]
        public void TimingTest()
        {
            // TODO unit test for the property 'Timing'
        }

    }

}
