/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesBay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesBayTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesBay
        //private TflApiPresentationEntitiesBay instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesBay
            //instance = new TflApiPresentationEntitiesBay();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesBay
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesBayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesBay
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesBay> (instance, "variable 'instance' is a TflApiPresentationEntitiesBay");
        }


        /// <summary>
        /// Test the property 'BayType'
        /// </summary>
        [Test]
        public void BayTypeTest()
        {
            // TODO unit test for the property 'BayType'
        }
        /// <summary>
        /// Test the property 'BayCount'
        /// </summary>
        [Test]
        public void BayCountTest()
        {
            // TODO unit test for the property 'BayCount'
        }
        /// <summary>
        /// Test the property 'Free'
        /// </summary>
        [Test]
        public void FreeTest()
        {
            // TODO unit test for the property 'Free'
        }
        /// <summary>
        /// Test the property 'Occupied'
        /// </summary>
        [Test]
        public void OccupiedTest()
        {
            // TODO unit test for the property 'Occupied'
        }

    }

}
