/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesJourneyPlannerRouteOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesJourneyPlannerRouteOptionTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesJourneyPlannerRouteOption
        //private TflApiPresentationEntitiesJourneyPlannerRouteOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesJourneyPlannerRouteOption
            //instance = new TflApiPresentationEntitiesJourneyPlannerRouteOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesJourneyPlannerRouteOption
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesJourneyPlannerRouteOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesJourneyPlannerRouteOption
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesJourneyPlannerRouteOption> (instance, "variable 'instance' is a TflApiPresentationEntitiesJourneyPlannerRouteOption");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Directions'
        /// </summary>
        [Test]
        public void DirectionsTest()
        {
            // TODO unit test for the property 'Directions'
        }
        /// <summary>
        /// Test the property 'LineIdentifier'
        /// </summary>
        [Test]
        public void LineIdentifierTest()
        {
            // TODO unit test for the property 'LineIdentifier'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }

    }

}
