/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesStreet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesStreetTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesStreet
        //private TflApiPresentationEntitiesStreet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesStreet
            //instance = new TflApiPresentationEntitiesStreet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesStreet
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesStreetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesStreet
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesStreet> (instance, "variable 'instance' is a TflApiPresentationEntitiesStreet");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Closure'
        /// </summary>
        [Test]
        public void ClosureTest()
        {
            // TODO unit test for the property 'Closure'
        }
        /// <summary>
        /// Test the property 'Directions'
        /// </summary>
        [Test]
        public void DirectionsTest()
        {
            // TODO unit test for the property 'Directions'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Test]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
        /// <summary>
        /// Test the property 'SourceSystemId'
        /// </summary>
        [Test]
        public void SourceSystemIdTest()
        {
            // TODO unit test for the property 'SourceSystemId'
        }
        /// <summary>
        /// Test the property 'SourceSystemKey'
        /// </summary>
        [Test]
        public void SourceSystemKeyTest()
        {
            // TODO unit test for the property 'SourceSystemKey'
        }

    }

}
