/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesRouteSearchMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesRouteSearchMatchTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesRouteSearchMatch
        //private TflApiPresentationEntitiesRouteSearchMatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesRouteSearchMatch
            //instance = new TflApiPresentationEntitiesRouteSearchMatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesRouteSearchMatch
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesRouteSearchMatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesRouteSearchMatch
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesRouteSearchMatch> (instance, "variable 'instance' is a TflApiPresentationEntitiesRouteSearchMatch");
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'LineName'
        /// </summary>
        [Test]
        public void LineNameTest()
        {
            // TODO unit test for the property 'LineName'
        }
        /// <summary>
        /// Test the property 'LineRouteSection'
        /// </summary>
        [Test]
        public void LineRouteSectionTest()
        {
            // TODO unit test for the property 'LineRouteSection'
        }
        /// <summary>
        /// Test the property 'MatchedRouteSections'
        /// </summary>
        [Test]
        public void MatchedRouteSectionsTest()
        {
            // TODO unit test for the property 'MatchedRouteSections'
        }
        /// <summary>
        /// Test the property 'MatchedStops'
        /// </summary>
        [Test]
        public void MatchedStopsTest()
        {
            // TODO unit test for the property 'MatchedStops'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }

    }

}
