/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesCarParkOccupancy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesCarParkOccupancyTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesCarParkOccupancy
        //private TflApiPresentationEntitiesCarParkOccupancy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesCarParkOccupancy
            //instance = new TflApiPresentationEntitiesCarParkOccupancy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesCarParkOccupancy
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesCarParkOccupancyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesCarParkOccupancy
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesCarParkOccupancy> (instance, "variable 'instance' is a TflApiPresentationEntitiesCarParkOccupancy");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Bays'
        /// </summary>
        [Test]
        public void BaysTest()
        {
            // TODO unit test for the property 'Bays'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CarParkDetailsUrl'
        /// </summary>
        [Test]
        public void CarParkDetailsUrlTest()
        {
            // TODO unit test for the property 'CarParkDetailsUrl'
        }

    }

}
