/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TflApiPresentationEntitiesStopPointCategory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TflApiPresentationEntitiesStopPointCategoryTests
    {
        // TODO uncomment below to declare an instance variable for TflApiPresentationEntitiesStopPointCategory
        //private TflApiPresentationEntitiesStopPointCategory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TflApiPresentationEntitiesStopPointCategory
            //instance = new TflApiPresentationEntitiesStopPointCategory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TflApiPresentationEntitiesStopPointCategory
        /// </summary>
        [Test]
        public void TflApiPresentationEntitiesStopPointCategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TflApiPresentationEntitiesStopPointCategory
            //Assert.IsInstanceOfType<TflApiPresentationEntitiesStopPointCategory> (instance, "variable 'instance' is a TflApiPresentationEntitiesStopPointCategory");
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'AvailableKeys'
        /// </summary>
        [Test]
        public void AvailableKeysTest()
        {
            // TODO unit test for the property 'AvailableKeys'
        }

    }

}
