@startuml
class DijkstraNetworkTests {
    - _network : Network
    - _tubeNetwork : Network
    + SetUp() : void
    + Dijkstra_FindsPath() : void
    + Dijkstra_SetsIntermediate() : void
    + RandomRoute_HasIntermediate() : void
    + AdjacentStations_NoIntermediate() : void
    + TubeNetwork_AdjacentStationsNoIntermediate() : void
    + RandomRoute_CostAccurate() : void
    + TubeNetwork_RouteCostEqualToSegmentSum() : void
    + Swap_SwapsStations() : void
    + Swap_UpdatesCosts() : void
    + Swap_UpdatesPath() : void
}
@enduml
