@startuml
class LinkTests {
    - _stubStation1 : Station
    - _stubStation2 : Station
    - _link : Link
    + SetUp() : void
    + Constructor_SetsDetails() : void
    + SetDuration_ChangesDurationAttribute() : void
    + SetLine_ChangesLineAttribute() : void
    + SetDurationMoreThanOnce_ThrowsException() : void
    + SetLineMoreThanOnce_ThrowsException() : void
}
@enduml
