@startuml
class LinkTests {
    + SetUp() : void
    + Constructor_SetsDetails() : void
    + SetDuration_ChangesDurationAttribute() : void
    + SetLine_ChangesLineAttribute() : void
    + SetDurationMoreThanOnce_ThrowsException() : void
    + SetLineMoreThanOnce_ThrowsException() : void
}
LinkTests --> "_stubStation1" Station
LinkTests --> "_stubStation2" Station
LinkTests --> "_link" Link
@enduml
