@startuml
class NetworkTests {
    - _network : Network
    + SetUp() : void
    + SwapInsert_InsertsStation() : void
    + SwapInsert_UpdatesStations() : void
    + SwapInsert_UpdatesCost() : void
    + CostFunction_CorrectCost() : void
    + SwapInsert_UpdatesRoute() : void
    + VerifyTestNetworkCosts() : void
    + TestNetwork_CostSymmetric() : void
    + RecalculateRoute_DataAccurate() : void
}
@enduml
