@startuml
class Tests {
    - _stat1 : Station
    - _stat2 : Station
    + Setup() : void
    + Constructor_SetsNaptan() : void
    + Constructor_SetsName() : void
    + AddingLink_UpdatesGetLinks() : void
    + AddingLink_UpdatesHasLink() : void
}
@enduml
