@startuml
class FloydCostNetwork {
    + FloydCostNetwork(logger:ILogger)
    <<internal>> <<override>> Initialise() : void
    + <<override>> CostFunction(startId:string, endId:string) : int
    - PreprocessFloyd() : void
    + EnumerateCostMatrix() : string
}
class "Dictionary`2"<T1,T2> {
}
Network <|-- FloydCostNetwork
FloydCostNetwork --> "_costMatrix<string,Dictionary<string, int>>" "Dictionary`2"
@enduml
