@startuml
enum NetworkType {
    Simple,
    Floyd,
    Dijkstra,
}
class NetworkFactory {
    + NetworkFactory(dataSource:INetworkDataSource)
    + Generate(type:NetworkType, logger:ILogger) : Network
}
NetworkFactory --> "_dataSource" INetworkDataSource
@enduml
