@startuml
enum NetworkType {
    Simple,
    Floyd,
    Dijkstra,
}
class NetworkFactory {
    + NetworkFactory(dataSource:INetworkDataFetcher)
    + Generate(type:NetworkType, logger:ILogger) : Network
}
@enduml
