@startuml
struct Route {
    + Count : int <<get>>
    + Cost : int <<get>>
    + Duration : int <<get>>
    + Route(stations:List<string>, cost:int, intermediateStations:List<List<string>>?)
    + Route(stations:List<string>)
    + <<override>> ToString() : string
    + UpdateCost(newCost:int) : void
    - InterStationCount() : int
    + InterCount : int <<get>>
}
class "List`1"<T> {
}
Route --> "TargetStations<string>" "List`1"
Route --> "InterStations<List<string>>" "List`1"
@enduml
