@startuml
class Route {
    + TargetStations : List<string>
    + IntermediateStations : List<List<string>>
    - _duration : TimeSpan
    - _cost : int
    + Count : int <<get>>
    + Cost : int <<get>>
    + Duration : TimeSpan <<get>>
    + Route(stations:List<string>, duration:TimeSpan, cost:int, intermediateStations:List<List<string>>?)
    + Route(stations:List<string>)
    + <<override>> ToString() : string
    + GetTargetPath() : List<string>
    <<internal>> GetIntermediateStations(segmentIndex:int) : List<string>
    <<internal>> GetIntermediateStations() : List<List<string>>
    + UpdateDuration(newDuration:TimeSpan) : void
    + UpdateCost(newCost:int) : void
    + UpdateIntermediateStations(segmentIndex:int, updateTo:List<string>) : void
    + Copy() : Route
    + InterStationCount() : int
}
@enduml
