/* 
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OccupancyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OccupancyApiTests
    {
        private OccupancyApi _instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            _instance = new OccupancyApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OccupancyApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OccupancyApi
            //Assert.IsInstanceOfType(typeof(OccupancyApi), instance, "instance is a OccupancyApi");
        }

        
        /// <summary>
        /// Test OccupancyGet
        /// </summary>
        [Test]
        public void OccupancyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.OccupancyGet(id);
            //Assert.IsInstanceOf<TflApiPresentationEntitiesCarParkOccupancy> (response, "response is TflApiPresentationEntitiesCarParkOccupancy");
        }
        
        /// <summary>
        /// Test OccupancyGetAllChargeConnectorStatus
        /// </summary>
        [Test]
        public void OccupancyGetAllChargeConnectorStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OccupancyGetAllChargeConnectorStatus();
            //Assert.IsInstanceOf<List<TflApiPresentationEntitiesChargeConnectorOccupancy>> (response, "response is List<TflApiPresentationEntitiesChargeConnectorOccupancy>");
        }
        
        /// <summary>
        /// Test OccupancyGetBikePointsOccupancies
        /// </summary>
        [Test]
        public void OccupancyGetBikePointsOccupanciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> ids = null;
            //var response = instance.OccupancyGetBikePointsOccupancies(ids);
            //Assert.IsInstanceOf<List<TflApiPresentationEntitiesBikePointOccupancy>> (response, "response is List<TflApiPresentationEntitiesBikePointOccupancy>");
        }
        
        /// <summary>
        /// Test OccupancyGetChargeConnectorStatus
        /// </summary>
        [Test]
        public void OccupancyGetChargeConnectorStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> ids = null;
            //var response = instance.OccupancyGetChargeConnectorStatus(ids);
            //Assert.IsInstanceOf<List<TflApiPresentationEntitiesChargeConnectorOccupancy>> (response, "response is List<TflApiPresentationEntitiesChargeConnectorOccupancy>");
        }
        
        /// <summary>
        /// Test OccupancyGet_0
        /// </summary>
        [Test]
        public void OccupancyGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OccupancyGet_0();
            //Assert.IsInstanceOf<List<TflApiPresentationEntitiesCarParkOccupancy>> (response, "response is List<TflApiPresentationEntitiesCarParkOccupancy>");
        }
        
    }

}
