@startuml
class Program {
    - {static} _logger : ILogger
    - {static} Main(args:string[]) : void
    - {static} TestTubeGen() : void
    - {static} WriteStationsToFile() : void
    - {static} TestTubeGenFloyd() : void
    - {static} LinearNetworkTestRouting() : void
    - {static} GetCachePath() : string
}
@enduml
